Integrate the Attitude Controller and Update Pointing Strategies
pathfinder-for-autonomous-navigation/FlightSoftware pull request #488
Opened 2020-09-06 01:41 UTC by kkrol27

# Integrate the Attitude Controller and Update Pointing Strategies

Fixes #287

### Summary of changes

- The `AttitudeComputer` and `ADCSCommander` control tasks were merged into a single control task called `AttitudeController`.
- The attitude controller from the PSim repository was integrated into the control task along with the detumbler.
- Pointing strategies were updated; see the switch statement comments in `AttitudeController.cpp` for more information.
- ...

### Testing

Describe your unit and functional testing. The testing should be at a level appropriate to demonstrate that your feature is sufficiently tested.

If you've got HITL or HOOTL run logs, the logs should go under the "Pull Request HITL Logs" [folder](https://cornellprod-my.sharepoint.com/personal/saa243_cornell_edu/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fsaa243%5Fcornell%5Fedu%2FDocuments%2FOAAN%20Team%20Folder%2FSubsystems%2FSoftware%2FPull%20Request%20HITL%20Testing%20Logs) on the OneDrive. Create a new subfolder with the # of this PR and put your items there. Note: the logs can be found after ptesting at `ptest/logs` (pick the appropriately dated folder for the log containing a successful run.)

The logs can be read via the ptest standalone plotter utility. See ptest/ for more details.

If your update does not require significant testing, argue why, or if you're deferring testing to another PR, create an issue ticket for the deferral and link it.

### Constants

Describe any important diffs to the `constants` file in the root level of the repository. Ensure that any constants you added to the code successfully made it into the `constants` file. If not, wrap the missing constants with `TRACKED_CONSTANT` macros and fix `constants_reporter.py` if necessary.

### Telemetry

Describe any important diffs to the `telemetry` file in the root level of the repository. Ensure that any telemetry you added to the code successfully made it into the `telemetry` file.

Also, take the opportunity to add the telemetry into the appropriate flows in src/flow_data.csv

### Documentation Evidence

2020-09-06 03:26 UTC, tanishqaggarwal requested changes
Made a quick pass

2020-09-06 03:26 UTC, tanishqaggarwal commented on src/fsw/FCCode/AttitudeController.cpp
> +    switch (state) {
It's pretty slick to set up the cases like this so that they cascade into each other but I'm worried about subtle bugs cropping up later because we change this code and accidentally forget to put in a `break` where it's needed. Do you think that'll be a problem?

2020-09-06 03:26 UTC, tanishqaggarwal commented on src/fsw/FCCode/AttitudeController.cpp
> +         * TODO : Implement control for zero torque and zero L.
Please do set up a ticket for this once this PR is more ready, so that we don't forget to track the work

2020-09-06 03:26 UTC, tanishqaggarwal commented on src/fsw/FCCode/AttitudeController.cpp
> +    m_body_cmd_f.set(lin::zeros<lin::Vector3f>());
Why not just call default_actuator_commands() here?

2020-09-06 03:26 UTC, tanishqaggarwal commented on src/fsw/FCCode/AttitudeController.cpp
> +        case adcs_state_t::point_standy:
Typo here: point_standy
```suggestion
        case adcs_state_t::point_standby:
```

2020-09-06 03:26 UTC, tanishqaggarwal commented on src/fsw/FCCode/AttitudeController.cpp
> +        pointer_vec1_current_f("attitude.pointer_vec1_current", Serializer<lin::Vector3f>(0, 1, 100)),
To reduce serializer constant verification burden, could you set these constants to be reasonable prior to merging in the PR?

2020-09-06 03:26 UTC, tanishqaggarwal commented on src/fsw/FCCode/AttitudeController.cpp
> +    m_body_cmd_f.set(lin::zeros<lin::Vector3f>());
This is actually unnecessary since default_actuator_commands is called at the beginning of execute().

2020-09-06 03:26 UTC, tanishqaggarwal commented on src/fsw/FCCode/AttitudeController.cpp
> +void AttitudeController::calculate_pointing_controller() {
You didn't NaN the controller outputs here. It's not necessary since execute() does it, but just wanted to point out there's an inconsistency with calculate_detumble_controller so that we can choose a convention

2020-09-06 03:26 UTC, tanishqaggarwal commented on src/fsw/FCCode/FieldCreatorTask.hpp
> +      ReadableStateField<unsigned long> time;
Or pan_time_f

2020-09-06 03:41 UTC, tanishqaggarwal commented on src/fsw/FCCode/AttitudeController.hpp
> +    union {
I got it, it just saves a little memory. I'm a little wary of this feature in C++ because I've rarely used it before but if it works, it works. It does introduce some extra burden of care around initializing values.

2020-09-06 03:41 UTC, tanishqaggarwal commented on src/fsw/FCCode/AttitudeController.hpp
> +    union {
Why not just allow these values to be temporaries?

2020-09-07 16:15 UTC, kkrol27 commented on src/fsw/FCCode/AttitudeController.cpp
> +        pointer_vec1_current_f("attitude.pointer_vec1_current", Serializer<lin::Vector3f>(0, 1, 100)),
I will be cleaning this up before trying to merge this PR.

2020-09-07 16:16 UTC, kkrol27 commented on src/fsw/FCCode/AttitudeController.cpp
> +    switch (state) {
I think it should be fine. I intentionally left this switch statement very empty so it reads as a very high level overview of our different attitude controller modes. I don't forsee this switch statement changing again.

2020-09-07 16:16 UTC, kkrol27 commented on src/fsw/FCCode/AttitudeController.cpp
> +         * TODO : Implement control for zero torque and zero L.
Will do.

2020-09-07 16:17 UTC, kkrol27 commented on src/fsw/FCCode/AttitudeController.cpp
> +void AttitudeController::calculate_pointing_controller() {
Will clean the handling of default outputs up.

2020-09-07 16:19 UTC, kkrol27 commented on src/fsw/FCCode/AttitudeController.hpp
> +    union {
They're pretty heavy objects which is why I made them a class member and allow them to overlap. The assumption here is that we'll either use the detumbler or pointer but never both. I could throw them on the stack if we're more comfortable with that.

2020-09-07 16:23 UTC, kkrol27 commented on src/fsw/FCCode/AttitudeController.hpp
> +    union {
This is something cool you can do with a union too - sorta a common basic example:

    union {
      struct {
        float x, y, z;
      };
      float v[3];
    };

2020-09-07 16:24 UTC, kkrol27 commented on src/fsw/FCCode/FieldCreatorTask.hpp
> +      ReadableStateField<unsigned long> time;
Ah no yep i need to update this! I actually haven't attempted to compile this yet so there are probably a lot of mistakes.

2020-09-07 16:25 UTC, kkrol27 commented on src/fsw/FCCode/FieldCreatorTask.hpp
> +        time("orbit.time", Serializer<unsigned long>()), // TODO : What are the serializer arguments
Ah - I think we're going with just a long actually. Do we support those?

2020-09-07 18:29 UTC, tanishqaggarwal commented on src/fsw/FCCode/AttitudeController.hpp
> +    union {
Neat. I think it's better for them to be temporaries? the actual speed loss should be very small. @athena255 thoughts?

2020-09-07 18:29 UTC, tanishqaggarwal commented on src/fsw/FCCode/FieldCreatorTask.hpp
> +        time("orbit.time", Serializer<unsigned long>()), // TODO : What are the serializer arguments
Nope, I think you have to specialize the template once more

2020-09-20 05:32 UTC, shihaocao commented on src/fsw/FCCode/AttitudeController.cpp
> +    switch (state) {
I think the cascading switch is better than the old way. It was really hard to figure out what would actually happen when.

2020-09-20 05:48 UTC, shihaocao commented on src/fsw/FCCode/AttitudeController.cpp
> +    control_pointing(pointer_state, pointer_data, pointer_actuation);
I dont think this method does any `set()`-ing of statefields, we'll need another block to set statefields properly

2020-09-20 05:51 UTC, shihaocao requested changes
Overall I think the high-level architecture looks good to me. I guess it'll just need a more throughout review when we move in all the proper MTR and Wheel decision modes into this control task from the old ADCSCommander.

2020-10-18 17:01 UTC, kkrol27 commented
Re-implemented on a separate branch -> closing.

2020-10-18 17:01 UTC, closed without merging