Cmdclient
pathfinder-for-autonomous-navigation/FlightSoftware pull request #503
Opened 2020-09-23 23:22 UTC by knk38

# Adding A Command Client to interact with RadioSession endpoints

### Summary of changes
- implemented methods to pause/unpause the uplink timer
- implemented methods to send/remove uplinks
- implemented the method to list all queued uplinks

If it applies, take a chance to describe offshoot work or TODOs that are a part of your PR.

### Testing
-When testing, I added print statements in each command that printed the content of the http GET/POST as well as the HTTP error code. (An code of 200 signified that the connection to the endpoint was successful) I made sure that each command printed 200.
-For the send and remove commands, I added a print statement in radiosession.py that printed "uplink sent" or "uplink removed" instead of actually sending the uplink to Iridium.

### Documentation Evidence
-there wasn't much documentation to be added, as I was implementing already documented methods

2020-09-23 23:59 UTC, knk38 commented on cmdclient/config.json
> +        "port" :
I wanted to keep this change to hide the server/port?

2020-09-24 00:13 UTC, tanishqaggarwal requested changes
Just a quick little suggested change

2020-09-24 00:13 UTC, tanishqaggarwal commented on cmdclient/__main__.py
> +            r = requests.post(url = endpoint, data = {"field":args[0],"value":args[1]})
This will only handle the first field in a set of fields.

2020-09-24 00:13 UTC, tanishqaggarwal commented on cmdclient/__main__.py
> +            r = requests.post(url = endpoint, data = {"field":args[0],"value":args[1]})
This will only handle the first specified field.

2020-09-24 00:13 UTC, tanishqaggarwal commented on cmdclient/config.json
> +        "port" :
Makes sense, although hiding this from the rest of the world isn't super critical since this is a general server configuration. Up to you if you want to leave it in

2020-09-24 00:41 UTC, fatimayousuf requested changes
Sorry it took me a while. I truly do not remember what I did for radio session, so I reviewed my old work  before looking at this pr 😅

2020-09-24 00:41 UTC, fatimayousuf commented on cmdclient/config.json
> +        "port" :
well it's just localhost, so it's not anything confidential

2020-09-24 00:41 UTC, fatimayousuf commented on ptest/http_cmd.py
> +        print("sent uplink")
I think we should keep SendMessage, since that is what will send the actual email to iridium

2020-09-24 00:41 UTC, fatimayousuf commented on cmdclient/__main__.py
> +        if len(args) > 2:
So if you go to ptest/endpoint_configs/radio_session/send_telem.yml, you'll see that this endpoint accepts a list of son objects. The list can be as long as you want. However, each of the json objects should only have two kay-value pairs, field and value. So an example of an args input might be:

[ {
          "field": dahkj
          "value": adkld
     },
     {
          "field":12daji34,
          "value: 380196
     },
     {
          "field": kodkwo
          "value": 8307
} ]

you should go through each json element of the list and check that there are only two key-value pairs: the field and the value.

2020-09-24 00:41 UTC, fatimayousuf commented on cmdclient/__main__.py
> +        if len(args) > 2:
Same comment as send_telem. look at ptest/endpoint_configs/radio_session/remove.yml to see the format of the input

2020-09-24 01:08 UTC, knk38 commented on cmdclient/__main__.py
> +        if len(args) > 2:
Okay thanks for this clarification, i fixed my helper method to follow this format for converting args

2020-09-24 01:10 UTC, knk38 commented on cmdclient/config.json
> +        "port" :
imma keep it secret just in case 😎

2020-09-24 01:17 UTC, tanishqaggarwal approved these changes

2020-09-24 01:20 UTC, fatimayousuf approved these changes
😄

2020-09-24 01:58 UTC, merged