Add bootcount to EEPROM
pathfinder-for-autonomous-navigation/FlightSoftware pull request #511
Opened 2020-10-04 20:03 UTC by madeleinemc

Add bootcount to EEPROM
Fixes #248

### Summary of changes
- Add "pan.bootcount" to eeprom_saved_fields
- Create bootcount field in FieldCreatorTask
- Increment bootcount in MissionManager constructor

### Testing
- Add test_bootcount in test_mission_manager
- Test that bootcount is in eeprom
- Test that bootcount initializes and increments correctly
- Test that deployment wait is 0 when bootcount is 2

### Telemetry
"pan.bootcount" is now in "eeprom_saved_fields"

### Documentation Evidence
There is associated commenting for every test line and hpp file entry.

2020-10-04 20:56 UTC, tanishqaggarwal requested changes

2020-10-04 20:56 UTC, tanishqaggarwal commented on src/fsw/FCCode/MissionManager.cpp
> +    is_deployed_f.set(false); // not necessarily true
This field is actually redundant now, since `is_deployed = bootcount > 1`. Consider removing the field

2020-10-04 20:56 UTC, tanishqaggarwal commented on test/test_fsw_EEPROM/test_fsw_EEPROM.cpp
> +    td::shared_ptr<ReadableStateField<unsigned int>> control_cycle_count_fp;
Syntax error here

2020-10-04 20:56 UTC, tanishqaggarwal commented on telemetry
> +            "flow_id": "undefined",
Since we added this field to the telemetry we should consider putting it in a flow so that we don't have to do more work later to organize the flows

2020-10-04 20:56 UTC, tanishqaggarwal commented on telemetry
> +            "bitsize": 7,
I think we should keep the bitsize 32, because it's possible this value might become large.

2020-10-04 20:56 UTC, tanishqaggarwal commented on test/test_fsw_mission_manager/test_fixture.cpp
> +    bootcount_shr_fp = registry.create_readable_field<unsigned int, 1000>("pan.bootcount");
What does shr stand for?

2020-10-04 20:56 UTC, tanishqaggarwal commented on test/test_fsw_mission_manager/test_mission_manager.cpp
> +    // Even if a significant amount of time passes, mission manager should still move to
thanks lol

2020-10-04 20:56 UTC, tanishqaggarwal commented on src/fsw/FCCode/MissionManager.cpp
> +    if (bootcount_fp->get() == 1) { //Can a serialized unsigned int be compared in this way?
Serialization does not affect the value of the field that can be accessed via `get` and `set`. It only affects the way the value is written to a bitstream for downlink/uplink.

2020-10-04 20:56 UTC, tanishqaggarwal commented on telemetry
> +            "flow_id": "undefined",
I think the "core state fields" flow is a good place to put it. You can modify `src/flow_data.csv` to add the field to this telemetry flow.

2020-10-04 20:58 UTC, madeleinemc commented on test/test_fsw_mission_manager/test_fixture.cpp
> +    bootcount_shr_fp = registry.create_readable_field<unsigned int, 1000>("pan.bootcount");
shared pointer, since there's another pointer below it

2020-10-04 21:13 UTC, tanishqaggarwal commented on test/test_fsw_mission_manager/test_fixture.cpp
> +    bootcount_shr_fp = registry.create_readable_field<unsigned int, 1000>("pan.bootcount");
Ah I should've shared this earlier: https://github.com/pathfinder-for-autonomous-navigation/FlightSoftware/wiki/Naming-Convention

2020-10-04 21:48 UTC, madeleinemc commented on test/test_fsw_mission_manager/test_fixture.cpp
> +    bootcount_shr_fp = registry.create_readable_field<unsigned int, 1000>("pan.bootcount");
There are two bootcount pointers in the text fixture. One is a pointer and one is a shared pointer, so that's why I named them that way. I will change the shared pointer to _fp instead of _shr_fp, but the other one is a regular (non-shared) pointer to a state field- what should I call it? The other regular pointers are also called _fp

2020-10-04 21:59 UTC, tanishqaggarwal commented on test/test_fsw_mission_manager/test_fixture.cpp
> +    bootcount_shr_fp = registry.create_readable_field<unsigned int, 1000>("pan.bootcount");
You should only really need 1 pointer I think, try removing uses of the non-shared pointer since it's secondary

2020-10-08 00:54 UTC, tanishqaggarwal approved these changes

2020-10-08 01:51 UTC, athena255 approved these changes

2020-10-08 01:51 UTC, athena255 commented on src/fsw/FCCode/FieldCreatorTask.hpp
> +        bootcount_f("pan.bootcount",Serializer<unsigned int>(4294967295), 1000)
consider adding this magic number (4294967295) to TRACKED_CONSTANTS

2020-10-08 01:51 UTC, athena255 commented on src/fsw/FCCode/MissionManager.cpp
> +    bootcount_fp = find_readable_field<unsigned int>("pan.bootcount", __FILE__, __LINE__);
@tanishqaggarwal  
Not sure if this is an issue, but should we account for the case where find_readable_field fails? I believe this method returns nullptr

2020-10-08 02:02 UTC, madeleinemc commented on src/fsw/FCCode/FieldCreatorTask.hpp
> +        bootcount_f("pan.bootcount",Serializer<unsigned int>(4294967295), 1000)
ah yes that's the max value for a 32-bit unsigned int. Is it worth adding to tracked constants or should I just add an inline comment?

2020-10-08 02:43 UTC, athena255 commented on src/fsw/FCCode/FieldCreatorTask.hpp
> +        bootcount_f("pan.bootcount",Serializer<unsigned int>(4294967295), 1000)
Oh in that case, it's fine. max values for 32-bit is typically represented in hex form 0xffffffff, but I think this is fine

2020-10-08 02:48 UTC, tanishqaggarwal commented on src/fsw/FCCode/MissionManager.cpp
> +    bootcount_fp = find_readable_field<unsigned int>("pan.bootcount", __FILE__, __LINE__);
Why does this method return nullptr?

2020-10-08 02:48 UTC, tanishqaggarwal commented on src/fsw/FCCode/MissionManager.cpp
> +    bootcount_fp = find_readable_field<unsigned int>("pan.bootcount", __FILE__, __LINE__);
If find_readable_field fails then all of flight software stops and won't even get to the first control cycle. We'd be able to detect this on HOOTL pretty much immediately.

2020-10-08 02:48 UTC, tanishqaggarwal commented on src/fsw/FCCode/FieldCreatorTask.hpp
> +        bootcount_f("pan.bootcount",Serializer<unsigned int>(4294967295), 1000)
Might be worth changing to 0xfffffff just to be extra clear.

2020-10-08 03:02 UTC, madeleinemc commented on src/fsw/FCCode/FieldCreatorTask.hpp
> +        bootcount_f("pan.bootcount",Serializer<unsigned int>(4294967295), 1000)
Sounds good, will do

2020-10-08 21:18 UTC, merged