Hardware stress test + Long Duration Gomspace Test
pathfinder-for-autonomous-navigation/FlightSoftware pull request #516
Opened 2020-10-11 19:57 UTC by afoarce

# PR Hardware stress test + Long Duration Gomspace Test

Fixes #401 

### Summary of changes
- Made a PTest checkout case for hardware stress testing (fire valves, turn docking, max speed on wheels)
- Made a PTest checkout case for Gomspace long duration testing (occasionally spin wheels/motor, fire valves)

### Testing

- HOOTL tested
- Needs to be HITL tested

### Documentation Evidence
The test case has in line documentation/logging that explains what it is doing.

2020-10-13 15:12 UTC, tanishqaggarwal approved these changes
The test structure looks good! I'd also loop @athena255, @fatimayousuf , and @shihaocao into this PR because it touches prop, Gomspace and ADCS. Maybe you guys don't need to review it thoroughly but please just stay abreast of what this PTest case entails.

2020-10-13 15:16 UTC, tanishqaggarwal requested changes
Oops I had more comments, for some reason they didn't come through.

2020-10-13 15:16 UTC, tanishqaggarwal commented on ptest/cases/gomspace_long_duration_case.py
> +from .base import SingleSatOnlyCase, TestCaseFailure
Shouldn't need testcasefailure

2020-10-13 15:16 UTC, tanishqaggarwal commented on ptest/cases/hardware_stress_test_case.py
> +        self.ws("dcdc.SpikeDock_cmd", "true") #should this be "true" or True ?
Should be True because `ws` is a smart function.

2020-10-13 15:16 UTC, tanishqaggarwal commented on ptest/cases/hardware_stress_test_case.py
> +            val = "1"
This val might be wrong, the value should be in milliseconds and greater than 3 or so in order for the valves to actually fire. Might be a good idea to set them to their max value of 1000

2020-10-13 15:16 UTC, tanishqaggarwal commented on ptest/cases/gomspace_long_duration_case.py
> +        if self.rs("pan.cycle_no")%2 == 0:
Same thing here, re: prop valve firing times

2020-10-13 15:16 UTC, tanishqaggarwal commented on ptest/cases/gomspace_long_duration_case.py
> +class GomspaceLongDurationCheckoutCase(SingleSatOnlyCase):
Since a lot of the utility functions are shared, consider splitting them out into a shared class and combining these two files. Python supports multiple inheritance and therefore allows "mixing in" functionality from another class.

2020-10-18 21:11 UTC, tanishqaggarwal commented on ptest/cases/hardware_stress_test_case.py
> +            val = "1"
Nevermind

2020-10-25 19:38 UTC, shihaocao commented on ptest/cases/gomspace_long_duration_case.py
> +        self.ws("adcs.state", Enums.adcs_states["point_manual"])
heads up, this will need a change of `point_manual` to `manual` pending newest PR

2020-11-09 04:34 UTC, tanishqaggarwal commented on ptest/cases/gomspace_long_duration_case.py
> +        self.adcs_spin_wheels_setup()
This setup stuff is common to both cases and could be abstracted away into the parent class.

2020-12-06 21:01 UTC, tanishqaggarwal approved these changes
Looks good!

2020-12-06 21:22 UTC, merged