Generic Plugin for OpenMCT
pathfinder-for-autonomous-navigation/FlightSoftware pull request #522
Opened 2020-10-25 16:45 UTC by Duncan-McD

# Generic Plugin for OpenMCT

fixes or partially fixes #385 ?

### Summary of changes

 - Created a generic plugin that took the same structure as other plugins we have used in the past
 - The generic plugin can take input to tell it which plugin to install
 - added JS object at the top of generic plugin to contain data for all the plugins
 - Merged historical and realtime telemetry plugins into generic plugin

### Testing

OpenMCT was tested with the example telemetry data sent into battery. Using this example data I was able to test displaying it in a generic form in OpenMCT which was successful. 

### Constants

N/A

### Telemetry

N/A

### Documentation Evidence
Documentation will be coming soon

2020-10-26 00:40 UTC, knk38 requested changes
Overall great work and congrats on your first PR! Just a few documentation things id suggest you add and some removal of old code that we don't really need anymore.

2020-10-26 00:40 UTC, knk38 commented on MCT/README.md
> +![Telemetry diagram](https://github.com/pathfinder-for-autonomous-navigation/FlightSoftware/blob/batteryinfo_mct/MCT/images/telemetry-diagram.PNG)
You should add some documentation here to replace/add to the previous plugin descriptions (maybe consider restructuring the sections in the readme?), also there definitely needs to be a section explaining how the new generic plugin works.

2020-10-26 00:40 UTC, knk38 commented on MCT/public/README.md
> +**more info on plugins and the object tree in the main MCT README**
Seconding my first comment, maybe change this section or add some stuff to it to make it relevant to our new plugin structure

2020-10-26 00:40 UTC, knk38 commented on MCT/server-files/battery-telemetry.js
> +const axios = require('axios')
Since we arent using axios anymore, you can remove this line

2020-10-26 00:40 UTC, knk38 commented on MCT/server-files/server.js
> +//var DummySpacecraft = require('./dummy_spacecraft');
delete old comment

2020-10-26 00:40 UTC, knk38 commented on MCT/server-files/server.js
> +if (process.argv[2] == "test") {
maybe consider taking out the call for spacecraft and making "npm start" call the battery instead? I don't think we need to use the spacecraft anymore honestly since we have already displayed openmct's capability to read in elasticsearch telemetry.

2020-10-26 00:40 UTC, knk38 commented on MCT/server-files/spacecraft.js
> +const axios = require('axios')
getting rid of axios here will break the spacecraft.js file, but im not sure we need it anymore honestly. Especially if we don't want openMCT to be sending telemetry to elasticsearch

2020-10-26 00:40 UTC, knk38 commented on MCT/public/generic-plugin.js
> +};
Some comments would be nice in this file to help explain the flow of logic, I don't think there is any in-line documentation

2020-11-02 09:08 UTC, tanishqaggarwal requested changes
Looks great! I agree with Kirin's recommendations for documentation and code cleanup. I've also made some of my own comments.

2020-11-02 09:08 UTC, tanishqaggarwal commented on MCT/server-files/battery-telemetry.js
> +          //"gomspace.get_hk": variables.get_hk,
When this PR is merged in can you add issue tickets for (a) making sure we add in the flight software telemetry that we need for these variables, (b) adding new variables to OpenMCT?

2020-11-02 09:08 UTC, tanishqaggarwal commented on MCT/server-files/battery-telemetry.js
> + battery-telemetry.js simulates the gomspace generating telemetry.
Might be worth reflecting that this is a simulator by renaming the file appropriately.

2020-11-02 09:08 UTC, tanishqaggarwal commented on MCT/server-files/domain-object.js
> +class DomainObject {
Does this declaration have to be in a single file?

2020-11-02 09:08 UTC, tanishqaggarwal commented on tlm/spam.go
> +package main
Is this file still required? If not, let's remove it. If it is, gitignore the compiled binary

2020-11-02 09:08 UTC, tanishqaggarwal commented on MCT/server-files/state-variables.js
> +//This file holds all of the variables to initialize every point on the gomspace battery and is called by other files that require variable access
Is this file still required?

2020-11-02 09:08 UTC, tanishqaggarwal commented on MCT/public/http.js
> +(function (root, factory) {
This looks like a module similar to requests. Is it used in the code? If not let's delete it.

2020-11-02 09:08 UTC, tanishqaggarwal commented on MCT/server-files/realtime-server.js
> +var express = require('express');
If this is copied from OpenMCT, let's say so at the top of this file so that it's known. Even better would be to move all of the OpenMCT boilerplate to some folder and call it boilerplate or something

2020-12-06 16:28 UTC, tanishqaggarwal commented on MCT/server-files/battery-telemetry.js
> +          //"gomspace.get_hk": variables.get_hk,
Resolved since you've already done this

2020-12-06 16:29 UTC, tanishqaggarwal commented on tlm/spam.go
> +package main
Let's keep it for now

2020-12-10 00:50 UTC, tanishqaggarwal requested changes
Looks great in the broad strokes! 

Btw: could you hit resolve when you've resolved one of my comments? Helps me keep track of what got fixed and which of my suggestions merits further discussion.

2020-12-10 00:50 UTC, tanishqaggarwal commented on MCT/public/generic-plugin.js
> +function getGeneric(j) {
Could this function potentailly be named something more descriptive?

2020-12-10 00:50 UTC, tanishqaggarwal commented on MCT/public/generic-plugin.js
> +                return http.get(url)
```suggestion
                return getGeneric(url);
```

2020-12-10 00:50 UTC, tanishqaggarwal commented on MCT/public/generic-plugin.js
> +                        if(domainObject.type === Object.values(value)[2]){
This if statement is inscrutable. Could you add either comments or variable names to make it clearer?

2020-12-10 00:50 UTC, tanishqaggarwal commented on MCT/public/generic-plugin.js
> +                    if(domainObject.type === Object.values(value)[2]){
Same deal here, with the if statement.

2020-12-10 00:50 UTC, tanishqaggarwal commented on MCT/server-files/telemetry.js
> +      let statesSubsystem= k;
```suggestion
    Object.entries(this.initialState).forEach(function ([statesSubsystem,v]) {
```

2020-12-10 00:50 UTC, tanishqaggarwal commented on MCT/server-files/telemetry.js
> +    console.log("Spacecraft Launched")
```suggestion
    console.log("Now reading spacecraft telemetry")
```

2020-12-10 00:50 UTC, tanishqaggarwal commented on MCT/server-files/telemetry.js
> +/*
Great work with the docstrings on this file.

2020-12-12 03:51 UTC, Duncan-McD commented on MCT/README.md
> +More on this can be found in the [MCT/Public Readme File]
I linked to the Other README file - the reason for having this second file is so that when I add the generator for the subsystem json files next PR the documentation and usage guide for that has a place to go that makes sense

2020-12-12 03:52 UTC, Duncan-McD commented on MCT/README.md
> +[Usage Guide]:
I tried to make the separation of the sections more clear here and organize it better

2020-12-12 03:56 UTC, Duncan-McD commented on MCT/README.md
> +[Main method and Server-files]: #main-method-and-server-files
Currently all the links to the files are broken because I made all the link variables have master instead of generic-plugin so that when it is merged in they will all work.

All the anchor links in the table of contents should work right now though.

2020-12-12 04:03 UTC, Duncan-McD commented on MCT/README.md
> +After generating the json file, Place it in the public/subsystems folder
I linked to the Other README file - the reason for having this second file is so that when I add the generator for the subsystem json files next PR the documentation and usage guide for that has a place to go that makes sense

2020-12-12 04:19 UTC, tanishqaggarwal approved these changes
Great work 👏

2020-12-12 04:19 UTC, tanishqaggarwal commented on MCT/README.md
> +# PAN Mission Control (OpenMCT)
Great! This file looks a lot better, thanks!

2020-12-12 20:38 UTC, knk38 approved these changes
Looks great, nice job!

2020-12-12 21:27 UTC, merged