PTest Hot Fixes
pathfinder-for-autonomous-navigation/FlightSoftware pull request #534
Opened 2020-11-06 20:53 UTC by shihaocao

# PTest Hot Fixes
--------------------------

### Fixes:
- Observed behavior: sometimes long lines get cut off when writing command to HITL through ptest. Observed when auto cycle not active. This is likely because when auto cycle is inactive, the debug console loops rapidly often attempting to read a command before it is finished, causing the command to not be completed.
- MTR pins still weren't working, changed some setup in MTorquerCase

### Summary of changes
- Minor changes to MTorquerCase
- debug_console now waits for the `\n` character

### Testing
- HITL tested with ADCSCheckoutCase and MTorquerCase
- Used fsw_teensy36_hitl_leader, and fsw_teensy36_test_mtr envs

### Constants
Uh debug_console constant?

### Telemetry
N/A

### Documentation Evidence
Todo

2020-11-06 21:07 UTC, knk38 approved these changes
yeah looks good, the changes all make sense

2020-11-06 21:07 UTC, knk38 commented on ptest/cases/torquer_rotate_case.py
> +        for val in range( 125, 501, 125 ): #start at 0.025 and ramp up by 0.025 until at 0.1
maybe change the comment or delete it altogether so it makes sense next to the code

2020-11-07 02:40 UTC, tanishqaggarwal requested changes

2020-11-07 02:40 UTC, tanishqaggarwal commented on ptest/cases/torquer_rotate_case.py
> +        self.torque_test( 0.056668)
@kkrol27 could you confirm if this value change is ok?

Shihao, could you add a link to source code here so that its 100% clear where the number is from?

2020-11-07 02:40 UTC, tanishqaggarwal commented on src/common/debug_console.cpp
> +    char lastchar = '\n';
Can you add some more comments on why this code is structured the way it is?

2020-11-08 22:19 UTC, shihaocao commented on ptest/cases/torquer_rotate_case.py
> +        self.torque_test( 0.056668)
@kkrol27

2020-11-08 23:17 UTC, tanishqaggarwal approved these changes

2020-11-08 23:17 UTC, tanishqaggarwal commented on src/common/debug_console.cpp
> +    i < SERIAL_BUF_SIZE && (Serial.available() || lastchar != '\n'); i++) {
I don't like the loop structure here--I personally prefer to let the second condition be a breaking if-statement in the loop body--but it works.

2020-11-08 23:31 UTC, shihaocao commented on src/common/debug_console.cpp
> +    i < SERIAL_BUF_SIZE && (Serial.available() || lastchar != '\n'); i++) {
Yeah in hindsight probably could've been a bit more clear

2020-11-08 23:32 UTC, merged