Prop fill env
pathfinder-for-autonomous-navigation/FlightSoftware pull request #535
Opened 2020-11-07 03:36 UTC by madeleinemc

# Prop filling environment 

Fixes #524 

### Summary of changes
- Created the prop_fill environment in PlatformIO, which runs the prop filling code with gomspace pings (in src/prep).

After this gets approved, I'll add it to the Pre-Integration Procedures documentation.

### Testing
Builds successfully (pio run -e prop_fill)

2020-11-07 04:40 UTC, tanishqaggarwal requested changes
The file compiles for me, I just want to be careful with what options we use for compilation.

2020-11-07 04:40 UTC, tanishqaggarwal commented on src/prep/FillingSequence.ino
> +
I would just get rid of this file to reduce confusion

2020-11-07 04:40 UTC, tanishqaggarwal commented on configs/prop_fill_env.ini
> +extends = teensy36
I would actually not extend teensy bc I don't know how all the additional flags in that environment affect this file. Could you use the base teensy framework that's specified in the platformIO documentation instead?

2020-11-12 02:42 UTC, madeleinemc commented
note that the most recent commit has only been tested on a teensy35 (on modified code) and not a teensy36 (but the code is for a teensy36)

2020-11-12 02:54 UTC, tanishqaggarwal approved these changes
🇺🇸 🚀 🇺🇸💥 🇺🇸

2020-11-13 21:58 UTC, merged