PTest Changes to Support C++ PSim
pathfinder-for-autonomous-navigation/FlightSoftware pull request #545
Opened 2020-11-12 04:05 UTC by shihaocao

# PTest Changes to Support C++ PSim

Fixes #. (Optional; sometimes PRs don't have an associated ticket)

### Summary of changes
- Rip matlab sim
- PTest mapping configuration files
- More configuration required out of ptest cases
-- Blah
-- Blah blah
- Bump psim pointer to latest master (ci.txt)

If it applies, take a chance to describe offshoot work or TODOs that are a part of your PR.

### Testing
Describe your unit and functional testing. The testing should be at a level appropriate to demonstrate that your feature is sufficiently tested.

If you've got HITL or HOOTL run logs, the logs should go under the "Pull Request HITL Logs" [folder](https://cornellprod-my.sharepoint.com/personal/saa243_cornell_edu/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fsaa243%5Fcornell%5Fedu%2FDocuments%2FOAAN%20Team%20Folder%2FSubsystems%2FSoftware%2FPull%20Request%20HITL%20Testing%20Logs) on the OneDrive. Create a new subfolder with the # of this PR and put your items there. Note: the logs can be found after ptesting at `ptest/logs` (pick the appropriately dated folder for the log containing a successful run.)

The logs can be read via the ptest standalone plotter utility. See ptest/ for more details.

If your update does not require significant testing, argue why, or if you're deferring testing to another PR, create an issue ticket for the deferral and link it.

### Constants
Describe any important diffs to the `constants` file in the root level of the repository. Ensure that any constants you added to the code successfully made it into the `constants` file. If not, wrap the missing constants with `TRACKED_CONSTANT` macros and fix `constants_reporter.py` if necessary.

### Telemetry
Describe any important diffs to the `telemetry` file in the root level of the repository. Ensure that any telemetry you added to the code successfully made it into the `telemetry` file.

Also, take the opportunity to add the telemetry into the appropriate flows in src/flow_data.csv.

### Documentation Evidence
Post to ReadTheDocs, or
- Argue that your inline documentation is sufficient.
- Create a issue ticket deferring the documentation task.

2020-11-13 16:13 UTC, kkrol27 commented
@shihaocao I'd update CI in FSW to reflect the changes here: https://github.com/pathfinder-for-autonomous-navigation/psim/pull/272

There's no longer a need to make a virtual environment within `lib/common/psim`!

2020-11-13 21:57 UTC, tanishqaggarwal commented on .github/workflows/hootl.yml
>          pip install -r requirements.txt
Could you also modify this file to run all of the existing ptest cases that require a simulation?

2020-11-15 23:04 UTC, shihaocao commented on .github/workflows/hootl.yml
>          pip install -r requirements.txt
Oops, just added

2020-11-16 02:37 UTC, shihaocao commented on ptest/psim/simulation.py
> +            fp.write(self.log)
not new code, just github freaking out

2020-11-16 18:08 UTC, tanishqaggarwal requested changes
Great work. I know this took a lot of effort so I'm surprised by how clean the resulting code ended up being.

2020-11-16 18:08 UTC, tanishqaggarwal commented on ptest/usb_session.py
> +    def case_interaction_setup(self, _debug_to_console):
Why not just make this part of __init__?

2020-11-16 18:08 UTC, tanishqaggarwal commented on ptest/cases/utils.py
> +        if self.skip_startup and self.desired_boot_state == "standby"  and not self.finished:
Instead of all of these "and not self.finished", might be worth just adding an explicit if-statement for `if self.finished`?

2020-11-18 22:41 UTC, shihaocao commented on ptest/psim/mapping_configs/README.md
> +"fc_vs_sim_s":{
I think it's nice to have that organizational separation just for the programmer to know that ptest + psim is a two way street. Also, it's required as usually fields that are read "from psim into fc" and "from fc into psim" are mutually exclusive

2020-11-18 22:42 UTC, shihaocao commented on ptest/psim/simulation.py
> +import psim # woo!
oops forgot to take out a lot of these comments

2020-11-19 02:23 UTC, shihaocao commented on ptest/README.md
> +# Installing C++ Psim
@kkrol27 I think the philosophy was to try and actually force the user to do it?

2020-11-19 02:30 UTC, kkrol27 commented on .github/workflows/hootl.yml
>          pip install -r requirements.txt
How long is CI gonna take to run after this lmao

2020-11-19 02:31 UTC, shihaocao commented on .github/workflows/hootl.yml
>          pip install -r requirements.txt
I'm not sure which other cases you were referring to? @tanishqaggarwal

2020-11-19 02:32 UTC, shihaocao commented on ptest/cases/base.py
> +from ..psim import MatlabSimulation, CppSimulation
I'll do it in another PR, so that we don't obliterate git history

2020-11-19 02:32 UTC, kkrol27 commented on ptest/README.md
> +# Installing C++ Psim
Hmmm I think it'd be best to either defer it at least or just push it on the user.

2020-11-19 02:35 UTC, shihaocao commented on ptest/cases/psim_debug.py
> +        # Start the spacecraft with zero angular rate in the body frame,
Oops outdated, will remove

2020-11-19 02:37 UTC, kkrol27 commented on ptest/README.md
> +# Installing C++ Psim
Not sure how much overhead it is to called pip things.

2020-11-19 02:43 UTC, shihaocao commented on ptest/usb_session.py
> +    def case_interaction_setup(self, _debug_to_console):
since the usb_session constructors are actually called in PTest and not in a PTestCase

2020-11-19 03:00 UTC, kkrol27 commented on ptest/psim/simulation.py
> +                        raise RuntimeError("Unexpected List Length, can't change into lin Vector")
I'd just add `lin.Vector2`.

2020-11-19 03:21 UTC, tanishqaggarwal commented on .github/workflows/hootl.yml
>          pip install -r requirements.txt
Basically all of the cases that are not currently in CI, should now be runnable in CI since they are no longer dependent on matlab.

2020-11-19 03:22 UTC, tanishqaggarwal commented on ptest/usb_session.py
> +    def case_interaction_setup(self, _debug_to_console):
Oh rip. Good point.

2020-11-19 03:24 UTC, tanishqaggarwal commented on ptest/psim/simulation.py
> +        # configs = ["truth/deployment","truth/base","sensors/base"]
I figured the intent of this comment was "if you are reading this code, here are some helpful folders to find config files in in psim" but this could be more explicit.

2020-11-19 03:25 UTC, tanishqaggarwal commented on ptest/psim/simulation.py
> +import lin
We can eat the cost of slow ptest bootups. Idk how much work lazy loading is, I've never done it before.

2020-11-19 03:27 UTC, tanishqaggarwal commented on ptest/README.md
> +# Installing C++ Psim
Let's just ignore this issue until it becomes an issue (I'm sure we'll notice if it does)

2020-11-19 03:27 UTC, tanishqaggarwal commented on configs/flight_and_test_envs.ini
> +[env:fsw_teensy36_hitl_leader_speed]
By "explain" I mean add comments in the file.

2020-11-19 19:05 UTC, kkrol27 commented on ptest/psim/simulation.py
> +import lin
Essentially we just move the imports into the `__init__` function of the simulation object because we don't need the libraries otherwise. Not a huge deal though anymore because we aren't tied to MATLAB.

2020-11-19 19:06 UTC, tanishqaggarwal commented on ptest/psim/simulation.py
> +import lin
Ah. If it's that simple, let's just do it so that HOOTL runs in CI take less time.

2020-11-22 18:32 UTC, shihaocao commented on ptest/cases/base.py
> +        return [""]
Yup, good catch

2020-11-22 18:35 UTC, shihaocao commented on ptest/cases/base.py
> +import psim # the actual python psim repo
I think for the sake of clarity it's probably best to just import here at the top unconditionally

2020-11-22 18:37 UTC, shihaocao commented on ptest/cases/base.py
> +import psim # the actual python psim repo
nvm, TIL about Lazy Importing, is CppSimulation that bloaty?

2020-11-22 18:39 UTC, shihaocao commented on ptest/psim/simulation.py
> +import lin
Would python actually call the `import`'s if a Simulation wasn't constructed though?

2020-11-22 18:47 UTC, shihaocao commented on ptest/psim/simulation.py
> +        raise NotImplementedError
Nope, I'll remove it.

2020-11-22 18:48 UTC, shihaocao commented on ptest/psim/simulation.py
> +        # configs = ["truth/deployment","truth/base","sensors/base"]
Oops nah, just outdated.

2020-11-22 19:46 UTC, kkrol27 approved these changes

2020-11-22 19:47 UTC, tanishqaggarwal approved these changes

2020-11-22 21:09 UTC, merged