Adding Reset for Flight Test case and adding cycle.start/cycle.auto to EEPROM
pathfinder-for-autonomous-navigation/FlightSoftware pull request #546
Opened 2020-11-13 19:53 UTC by knk38

# Reset for Flight Test case

Fixes # 

### Summary of changes
- Added a new test case that resets ppt_mode, bootcount, and starts autocycling
- Changed cycle.start and cycle.auto in DebugTask.cpp to be EEPROM saveable

If it applies, take a chance to describe offshoot work or TODOs that are a part of your PR.

### Testing
-I deleted the telemetry file in root and ran the telemetry info generator to ensure that the two new state fields showed up as EEPROM saved
-I also checked that the fields showed up in the eprom.json file
-I ran reset for flight, then the empty case with autocycling and then the reset for flight case afterwards to ensure that the test case didn't error out when already autocycling. 

### Telemetry
cycle.start and cycle.auto are now EEPROM saveable and update every cycle (EEPROM save period of 1).

### Documentation Evidence
Should be sufficient inline documentation for the new functions

2020-11-13 21:49 UTC, tanishqaggarwal requested changes

2020-11-13 21:49 UTC, tanishqaggarwal commented on ptest/cases/reset_for_flight.py
> +  def set_ppt(self):
I did some digging today on the flight units, and it turns out that we've got a bug with PPT modes: setting the PPT mode like this does nothing if the spacecraft is turned off again after this testcase (which it has to be.) See #547 for more details. Likely, as part of #547 we will have to change to this testcase to write the PPT mode _hardware setting_ via a different state field. But let's leave this in for now.

2020-11-13 21:49 UTC, tanishqaggarwal commented on ptest/cases/reset_for_flight.py
> +  def set_bootcount(self):
The code for set_ppt and set_bootcount is very similar and is code that could be broken out into its own function, maybe something like "ws_and_verify"?

2020-11-13 21:49 UTC, tanishqaggarwal commented on ptest/cases/reset_for_flight.py
> +    self.ws( "cycle.auto", True )
Need to cycle after applying this command.

2020-11-13 21:50 UTC, tanishqaggarwal commented
Can you also reset the deployment timer and deployment-related fields?

2020-11-13 22:41 UTC, knk38 commented
> Can you also reset the deployment timer and deployment-related fields?

Where can i find these fields?

2020-11-13 22:42 UTC, tanishqaggarwal commented
MissionManager.cpp

2020-11-13 22:42 UTC, knk38 commented on ptest/cases/reset_for_flight.py
> +  def set_ppt(self):
okay i will take a note of this as well

2020-11-13 22:50 UTC, knk38 commented on ptest/cases/reset_for_flight.py
> +    self.ws( "cycle.auto", True )
When I cycle after this command, FC throws an error that says I am cycling too quickly or something?
<img width="562" alt="Screen Shot 2020-11-13 at 5 49 45 PM" src="https://user-images.githubusercontent.com/56562686/99128373-9fda9c80-25d8-11eb-8382-8e9ec9506930.png">

2020-11-13 22:52 UTC, tanishqaggarwal commented on ptest/cases/reset_for_flight.py
> +    self.ws( "cycle.auto", True )
This is probably because autocycling is set to true in eeprom.json prior to booting up the testcase. Remove the file whenever you see this error

2020-11-16 00:51 UTC, tanishqaggarwal approved these changes

2020-11-16 00:51 UTC, tanishqaggarwal commented on MCT/server-files/battery-telemetry.js
> +/*
Remove this file

2020-11-16 00:53 UTC, knk38 commented on MCT/server-files/battery-telemetry.js
> +/*
omg i deleted it idk why it came back, maybe its still on my remote

2020-11-28 01:11 UTC, merged