Orbit control task
pathfinder-for-autonomous-navigation/FlightSoftware pull request #551
Opened 2020-11-17 00:15 UTC by fatimayousuf

# Orbit Control Task

Fixes #62 

### Summary of changes
- Added the orbit controller

### Testing
I made some unit tests testing different parts of the orbit controller. I think Kyle said we will test the entire behavior on psim. The tests are mostly self explanatory. 

`schedule_valves()` takes in an impulse in the body frame of the spacecraft and gives the time each valve should open by looking for the minimum linear combination of impulses on each of the thrusters. Since there are 4 thrusters and 3 spatial dimensions, it means that the system is overconstrained. I had to manually find the general solution to Ax=b (which took ages to finish). but it works! :D

2020-11-17 10:08 UTC, tanishqaggarwal reviewed
Looks great, code is nice and clean. Tests look solid. Just have a couple of questions and suggestions

Could you also get rid of the ptest/spam file?

2020-11-17 10:08 UTC, tanishqaggarwal commented on src/fsw/FCCode/OrbitController.cpp
> +    ctrl_cycles_per_cooling_period_fp = FIND_WRITABLE_FIELD(unsigned int, prop.ctrl_cycles_per_cooling);
Do we need the init function or are these state field pointers initializable as part of the control task's constructor? Genuinely asking because I don't remember where the OrbitController is in the control cycle loop, but I feel like it should be possible to eliminate this init() function.

2020-11-17 10:08 UTC, tanishqaggarwal commented on src/fsw/FCCode/OrbitController.cpp
> +void OrbitController::schedule_valves(lin::Vector3d J_body) {
Could you walk me through the algebra here at our next work session? I know it works, just wondering if there's any scope to simplify things.

2020-11-17 10:08 UTC, tanishqaggarwal commented on src/fsw/FCCode/OrbitController.hpp
> +     */
To improve this comment, maybe talk about how exactly it finds this time and why it's an estimation

2020-11-19 00:56 UTC, fatimayousuf commented on src/fsw/FCCode/OrbitController.cpp
> +    ctrl_cycles_per_cooling_period_fp = FIND_WRITABLE_FIELD(unsigned int, prop.ctrl_cycles_per_cooling);
the orbit controller goes after the attitude estimator and before the prop controller in the main control loop. I'll move the attitude estimator field to the constructor, but I guess we need the init() function for the prop stuff

2020-11-19 01:18 UTC, tanishqaggarwal commented on src/fsw/FCCode/OrbitController.cpp
> +    ctrl_cycles_per_cooling_period_fp = FIND_WRITABLE_FIELD(unsigned int, prop.ctrl_cycles_per_cooling);
Ok let's just keep as-is then.

2020-11-19 01:39 UTC, fatimayousuf commented on src/fsw/FCCode/OrbitController.cpp
> +    lin::Vector3d sun; // Points from the Earth to the sun
uhhh I just used the model that Kyle showed me a while ago. idk if there is a difference between this and the adcs vector. @kkrol27 ?

2020-11-19 02:17 UTC, kkrol27 requested changes
Overall structure looks great. Biggest outstanding issue is some trailing work for pesky coordinate frame conversion stuff; we can tag up about that though!

2020-11-19 02:17 UTC, kkrol27 commented on src/fsw/FCCode/OrbitController.cpp
> +    lin::Vector3d sun; // Points from the Earth to the sun
We want the sun vector in ECI actually because we're just worried about where we are in our orbit. Attitude isn't really relevant here.

2020-11-19 02:17 UTC, kkrol27 commented on src/fsw/FCCode/OrbitController.cpp
> +    lin::Vector3d proj_sun = sun - ( lin::dot(sun, orb_plane) * orb_plane );
I think we may want to normalize the projection of the sun vector into the orbital plane here?

2020-11-19 02:17 UTC, kkrol27 commented on src/fsw/FCCode/OrbitController.hpp
> +    void schedule_valves(lin::Vector3d J_body);
We can probably make some of these functions that take in vectors take them by constant reference as opposed to by value to prevent copies.

2020-11-19 02:17 UTC, kkrol27 commented on src/fsw/FCCode/OrbitController.cpp
> +        gnc::utl::rotate_frame(q_body_eci_d, J_eci, J_body);
You should just be able to do something like this with `lin` if you'd like to be less verbose:

    gnc::utl::rotate_frame(lin::cast<double>(q_body_eci).eval(), J_eci, J_body);

The `lin::cast<...>(...)` function will stream an element wise case of the `lin` type and `.eval()` with force the creation of a `lin::Vector<...>` type (in this case a `lin::Vector4d`).

2020-11-19 02:17 UTC, kkrol27 commented on src/fsw/FCCode/OrbitController.cpp
> +    if ( std::find(std::begin(firing_nodes), std::end(firing_nodes), theta) != std::end(firing_nodes) ) {
Sorry I'm not too familiar but are we trying to check if the satellite is exactly at a firing node here? That may be a little dangerous with floating point numbers...

2020-11-19 02:29 UTC, kkrol27 commented on src/fsw/FCCode/OrbitController.cpp
> +    lin::Vector3d proj_sun = sun - ( lin::dot(sun, orb_plane) * orb_plane );
nvm

2020-11-19 02:37 UTC, tanishqaggarwal approved these changes
Looks good to me!

2020-11-29 19:29 UTC, kkrol27 requested changes
Looks really good - only big thing is moving the calculation of velocity in `ecef0` out of that one function and into the main execute function!

2020-11-29 19:29 UTC, kkrol27 commented on src/fsw/FCCode/OrbitController.cpp
> +    // Get the sun vector in ECEF
```suggestion
```
We can probably just remove this comment or change it to say ECI.

2020-11-29 19:29 UTC, kkrol27 commented on src/fsw/FCCode/OrbitController.cpp
> +    lin::Vector3d orb_plane = lin::cross(r, v);
Sorry I didn't make an explicit comment about this before, but this `v` here is in `ecef` and we really need it to be in `ecef0` (a non-rotating version of `ecef` at this instant in time). If the distinction here doesn't make sense lmk and we can talk through it!

You'll need Earth's angular rate which is the same as `ecef`'s angular rate to do this conversion. There's an example of it happening here:

https://github.com/pathfinder-for-autonomous-navigation/psim/blob/167be53e93c3463542de343a7b2ebd84d4e4bb85/src/gnc/orbit_controller.cpp#L119-L138

`this_v_ecef0` is going to be the comparable variable.

2020-11-29 19:29 UTC, kkrol27 commented on src/fsw/FCCode/OrbitController.cpp
> +    if ( time_till_firing_cc < 20 && static_cast<prop_state_t>(prop_state_fp->get()) == prop_state_t::await_firing) {
Seems like we have a two second firing window then. This seems sufficient to me - @tanishqaggarwal just want to draw your attention to this. Should we maybe make the control cycle count window a tracked constant?

2020-11-29 19:29 UTC, kkrol27 commented on src/fsw/FCCode/OrbitController.cpp
> +}
Looks good. The only thing I'd say is we should have this function take in `vel` is `ecef0` so we don't need to do the `w_earth` and `vel - lin::cross(w_earth, pos)` in this function - it'll just be moved outside to fixed one of my previous comments.

2020-11-29 19:29 UTC, kkrol27 commented on src/fsw/FCCode/OrbitController.hpp
> +#include <algorithm>
I think this header isn't needed anymore? Either way, any headers that are only needed for an implementation is the `.cpp` file should be included there to prevent them being included in every other translation unit that pulls in the orbit controller header.

2020-11-29 21:47 UTC, kkrol27 approved these changes
Looks good to me!

2020-12-10 00:45 UTC, athena255 reviewed
Not sure if I'm missing something but it seems like the the PropController fields are not set here

2020-12-10 00:45 UTC, athena255 commented on src/fsw/FCCode/OrbitController.cpp
> +    if (time_till_firing_cc <= (prop_min_cycles_needed() + 10) && static_cast<prop_state_t>(prop_state_fp->get()) == prop_state_t::idle) {
Why do we need prop_min_cycles_needed() + 10?

2020-12-10 00:45 UTC, athena255 commented on src/fsw/FCCode/OrbitController.hpp
> +    WritableStateField<unsigned int>* prop_cycles_until_firing_fp;
Does the OrbitController set the schedules in the Prop Controller? It seems like these fields are declared here, and they do not use the PropController schedule fields

2020-12-10 01:19 UTC, fatimayousuf commented on src/fsw/FCCode/OrbitController.cpp
> +    if (time_till_firing_cc <= (prop_min_cycles_needed() + 10) && static_cast<prop_state_t>(prop_state_fp->get()) == prop_state_t::idle) {
I remember you said that the prop system needs some time to get ready to fire. I thought prop_min_cycles_needed() gave that amount of time? So if the satellite is nearly at a firing node, the orbit control task would let the prop system know that it has to fire soon by setting prop_cycles_until_firing_fp.

I guess I'm not totally sure how the prop system works. How is the orbit control task supposed to set the prop schedule again?

2020-12-10 01:21 UTC, fatimayousuf commented on src/fsw/FCCode/OrbitController.hpp
> +    WritableStateField<unsigned int>* prop_cycles_until_firing_fp;
No this is a pointer to a field declared from the prop controller 
`prop_cycles_until_firing_fp = FIND_WRITABLE_FIELD(unsigned int, prop.cycles_until_firing);`

Are you talking about the sched_valvex_f fields below? They were already there when I started this branch, so I kinda just guessed that those fields were how the prop system would know how long to open the valves.

2020-12-13 01:53 UTC, athena255 commented on src/fsw/FCCode/OrbitController.cpp
> +    if (time_till_firing_cc <= (prop_min_cycles_needed() + 10) && static_cast<prop_state_t>(prop_state_fp->get()) == prop_state_t::idle) {
Got it, makes sense. The orbit control task should just set prop schedule by writing to the sched_valve* values. The schedule needs to be set when it is in idle. When it detects a schedule, it will start going through the process of getting ready to fire such as pressurizing. The schedule can be changed as long as it is before Await_Firing iirc.

2020-12-13 22:36 UTC, athena255 approved these changes

2020-12-17 03:41 UTC, merged

2020-12-17 03:42 UTC, fatimayousuf commented
Thank you! @tanishqaggarwal