Dev/log
pathfinder-for-autonomous-navigation/FlightSoftware pull request #558
Opened 2020-11-26 23:08 UTC by shihaocao

Before opening the PR, think: 
- Is this PR bulletproof? Can I think of no ways to improve this PR beyond its current state?
- Is the PR short enough to ensure a quick but thorough review, but long enough to represent a complete feature? For large state machines, let's try opening PRs for only a few states at a time.

If the answer to either of these questions is "no", refactor your code and open your PR when the answer to both questions is "yes".

--------------------------

# PR Title

Fixes #. (Optional; sometimes PRs don't have an associated ticket)

### Summary of changes
- 
- 
-

If it applies, take a chance to describe offshoot work or TODOs that are a part of your PR.

### Testing
Describe your unit and functional testing. The testing should be at a level appropriate to demonstrate that your feature is sufficiently tested.

If you've got HITL or HOOTL run logs, the logs should go under the "Pull Request HITL Logs" [folder](https://cornellprod-my.sharepoint.com/personal/saa243_cornell_edu/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fsaa243%5Fcornell%5Fedu%2FDocuments%2FOAAN%20Team%20Folder%2FSubsystems%2FSoftware%2FPull%20Request%20HITL%20Testing%20Logs) on the OneDrive. Create a new subfolder with the # of this PR and put your items there. Note: the logs can be found after ptesting at `ptest/logs` (pick the appropriately dated folder for the log containing a successful run.)

The logs can be read via the ptest standalone plotter utility. See ptest/ for more details.

If your update does not require significant testing, argue why, or if you're deferring testing to another PR, create an issue ticket for the deferral and link it.

### Constants
Describe any important diffs to the `constants` file in the root level of the repository. Ensure that any constants you added to the code successfully made it into the `constants` file. If not, wrap the missing constants with `TRACKED_CONSTANT` macros and fix `constants_reporter.py` if necessary.

### Telemetry
Describe any important diffs to the `telemetry` file in the root level of the repository. Ensure that any telemetry you added to the code successfully made it into the `telemetry` file.

Also, take the opportunity to add the telemetry into the appropriate flows in src/flow_data.csv.

### Documentation Evidence
Post to ReadTheDocs, or
- Argue that your inline documentation is sufficient.
- Create a issue ticket deferring the documentation task.

2020-11-29 07:49 UTC, tanishqaggarwal requested changes

2020-11-29 07:49 UTC, tanishqaggarwal commented on ptest/cases/base.py
> +        # packet["t"] = int(self.sim.mysim["truth.t.ns"]/1e9/self.sim.dt) # t: number of cycles since sim start
```suggestion
```

2020-11-29 07:49 UTC, tanishqaggarwal commented on ptest/cases/base.py
> +        Read a psim state field with <name>, log to logger, and return the python value
```suggestion
        Read a psim state field with <name>, log to datastore, and return the python value
```

2020-11-29 07:49 UTC, tanishqaggarwal commented on ptest/cases/base.py
> +        Read a psim state field with <name>, log to logger, print to console and return the python value
```suggestion
        Read a psim state field with <name>, log to datastore, print to console and return the python value
```

2020-11-29 07:49 UTC, tanishqaggarwal commented on ptest/cases/psim_debug.py
> +        # self.data_logs()
```suggestion
```

2020-11-29 07:49 UTC, tanishqaggarwal commented on ptest/cases/psim_debug.py
>          pass
```suggestion
```

2020-11-29 07:49 UTC, tanishqaggarwal commented on ptest/cases/base.py
> +        self._devices = [self.flight_controller_leader, self.flight_controller_follower]
Why is `_devices` needed? This might conflict with some of @afoarce's work

2020-11-29 19:09 UTC, kkrol27 reviewed
Looks pretty good on the PSim end of things; just have the one question about using the `[...]` versus `get(...)` and then some of @tanishqaggarwal's concerns.

2020-11-29 19:09 UTC, kkrol27 commented on ptest/cases/base.py
>          ret = self.sim.mysim[name]
This can throw and exception if the field isn't found. Is that the kind of behavior that we want or would we rather use the `.get(...)` function that will return `None` if the field doesn't exist?

2020-11-29 19:09 UTC, kkrol27 commented on ptest/plotter.py
> +        if any(field.endswith(x) for x in ['.u', '.x', '.y', '.z']):
I can open a ticket up in PSim to correct this issue (i.e. rename angular rates from `w` to `omega`) if we'd like to go that route. It'd be a somewhat large refactoring but nothing more than an hour I'd say.

2020-11-29 20:19 UTC, tanishqaggarwal commented on ptest/plotter.py
> +        if any(field.endswith(x) for x in ['.u', '.x', '.y', '.z']):
I feel like this is a much clever and less work-intensive solution.

2020-11-29 23:27 UTC, kkrol27 commented on ptest/plotter.py
> +        if any(field.endswith(x) for x in ['.u', '.x', '.y', '.z']):
I'm not arguing with that at all haha - just didn't know if we'd eventually want to return to the `(x, y, z, w)` convention for four dimensional vectors eventually or not.

2020-11-30 04:58 UTC, shihaocao commented on ptest/plotter.py
> +        if any(field.endswith(x) for x in ['.u', '.x', '.y', '.z']):
I think this is the preferred method (with `.u`) since in general I'd like to minimize the length of these state field names haha

2020-11-30 05:06 UTC, shihaocao commented on ptest/cases/base.py
> +        self._devices = [self.flight_controller_leader, self.flight_controller_follower]
Needed some container to store all devices within the test case object to reference later (in order to be clean). Which work were you referring to?

2020-12-03 02:51 UTC, shihaocao commented on ptest/cases/base.py
>          ret = self.sim.mysim[name]
Sure thing, caught it with a slightly nicer error message too

2020-12-03 04:33 UTC, tanishqaggarwal approved these changes

2020-12-03 04:34 UTC, shihaocao commented on ptest/cases/base.py
> +        self._devices = [self.flight_controller_leader, self.flight_controller_follower]
Renamed to just self.devices

2020-12-05 22:16 UTC, merged