Autonomous mission manager
pathfinder-for-autonomous-navigation/FlightSoftware pull request #567
Opened 2020-12-06 21:20 UTC by afoarce

# Autonomous Mission Manager

Fixes #476 

### Summary of changes
- Added PTest case for radio HOOTL/HITL to test telemetry passing between spacecrafts
- Changes made to radio uplink logic resulting from radio HITL testing

### Testing
The case has been HOOTL testing and will be HITL tested soon as radio fixes are finalized.

### Constants
N/A

### Telemetry
N/A

### Documentation Evidence
- In line documentation shows the steps of the test case and radio session, additional documentation not required since it does not change how flight software functions.

2020-12-10 23:40 UTC, tanishqaggarwal requested changes

2020-12-10 23:40 UTC, tanishqaggarwal commented on ptest/cases/autonomous_mission_manager_case.py
> +
Can you add a function here that processes the raw orbital data and computes propagated orbits? We can have the function do nothing for now and add in propagation once it's ready. This way, according to the code specification, the AMC is always sending the latest, propagated orbit.

2020-12-10 23:40 UTC, tanishqaggarwal commented on ptest/cases/autonomous_mission_manager_case.py
> +            self.leader.write_multiple_states(baseline_orbit_data_fields, baseline_orbit_data_vals_leader)
So one problem with continuously calling write_multiple_states in a loop when `leader` or `follower` is a RadioSession is that the uplink timer keeps getting restarted (see [this line](https://github.com/pathfinder-for-autonomous-navigation/FlightSoftware/blob/master/ptest/radio_session.py#L154) in the definition of `write_multiple_states`). So the uplink will actually not get sent.

To prevent this, I think we should modify `uplink_queued` in RadioSession so that it _also_ returns true if there an `uplink.json` file exists. The existence of this file indicates that either the autonomous mission controller or a ground operator has tried to schedule an uplink to be sent up to the spacecraft.

By making this change, the call to `write_multiple_states` made in these two lines would be defeated by the `self.uplink_queued()` [check](https://github.com/pathfinder-for-autonomous-navigation/FlightSoftware/blob/master/ptest/radio_session.py#L140-L141) in `write_multiple_states`, and therefore the uplink timer won't keep getting restarted.

2020-12-10 23:40 UTC, tanishqaggarwal commented on ptest/cases/autonomous_mission_manager_case.py
> +            self.leader.write_multiple_states(baseline_orbit_data_fields, baseline_orbit_data_vals_leader)
The above comment I've made applies only to RadioSession, but here's a secondary thought I had: because `write_multiple_states` never fails if it's being used to send data over USB or to a HOOTL FSW instance, but it might fail if it's being used to send data over the radio, we therefore have a difference in the rates with which the spacecraft get information about each other's orbits in HOOTL vs. HITL. 

This might cause unforeseen problems if we end up over-relying on HOOTL testing to verify our orbit-matching algorithms (since an algorithm that constantly gets updates about spacecraft location is probably going to perform better than an algorithm that only gets it once in a while). Down the road (unless you want to implement this now), we might want to some kind of option to this testcase that occasionally stops this call to `write_multiple_states` in HOOTL in order to make the testcase more flight-like.

Thoughts?

2020-12-10 23:40 UTC, tanishqaggarwal commented on ptest/cases/autonomous_mission_manager_case.py
> +            return False
In order to end the mission we should send a command to _both_ spacecraft to go back to standby or safehold. I think we should add some calls to write_state in order to accomplish this.

Note, though, that if we call `write_state` here, but on a previous loop of `run_case` we called write_state to instead update the orbital positions, the call to `write_state` will fail in HITL if you implement my recommendation below. What do you think we should do about this?

2020-12-10 23:40 UTC, tanishqaggarwal commented on ptest/cases/autonomous_mission_manager_case.py
> +            return True
Yep, it should. So since the leader and follower have the same behavior, you might want to abstract away this code block and the earlier codeblock for the leader into a function

2020-12-10 23:40 UTC, tanishqaggarwal commented on ptest/cases/autonomous_mission_manager_case.py
> +            return False
This is a repetition of the same code twice, it should be possible to abstract this away into a function.

2020-12-17 00:48 UTC, athena255 commented on ptest/cases/autonomous_mission_manager_case.py
> +            return False
I think this is simple enough for it to be okay that it is repeated.

2020-12-17 00:54 UTC, afoarce commented on ptest/cases/autonomous_mission_manager_case.py
> +                pass
Currently I had it as a placeholder, ideally it should wait until data exists in the elasticsearch database but I don't know what the response is for fields that aren't there yet. Do we not need to check for this initial case before data is transmitted?

2020-12-17 01:06 UTC, fatimayousuf commented on ptest/cases/autonomous_mission_manager_case.py
> +                pass
I think I get what you're asking. If you try to search for a field that doesn't currently exist in the ElasticSearch database, then it will return `Unable to find field: {field} in index: {index}` (see tlm/webservice.py). I'm pretty sure the index would be statefield_report_[imei number], but idk if someone changed it since I last wrote ground software

2020-12-17 01:26 UTC, afoarce commented on ptest/cases/autonomous_mission_manager_case.py
> +            return False
Why is it that it would fail? If it does fail, would it be able to succeed on the next iteration?

2020-12-17 01:40 UTC, afoarce commented on ptest/cases/autonomous_mission_manager_case.py
> +            self.leader.write_multiple_states(baseline_orbit_data_fields, baseline_orbit_data_vals_leader)
That's a good point. For now I've updated RadioSession, I think as we do more HOOTL testing of this we can add random wait lengths or randomly decide if data will be written to slow down the connection.

2020-12-17 01:45 UTC, fatimayousuf commented on ptest/cases/autonomous_mission_manager_case.py
> +            self.leader.write_multiple_states(baseline_orbit_data_fields, baseline_orbit_data_vals_leader)
Ahhh I'm sorry I didn't even think of that when I was writing radio session. Yeah if you keep writing multiple states repeatedly, then the timer will restart again and again and it won't send the telemetry packets. I think what Tanishq wrote sounds right. Adding that extra condition to `uplink_queued` should take care of the problem?

2020-12-17 02:05 UTC, fatimayousuf commented on ptest/cases/autonomous_mission_manager_case.py
> +            self.leader.write_multiple_states(baseline_orbit_data_fields, baseline_orbit_data_vals_leader)
I think there should maybe be something here that checks if the uplink actually is sent? For example, if the uplink fails to send and `self.follower.write_multiple_states()` returns false, then it looks like that telemetry packet never gets sent to the other satellite. Also, the time of last comms should give the time of the last _successful_ uplink, not the last attempt to uplink

2020-12-17 02:14 UTC, fatimayousuf requested changes
It's so cool seeing everything start to come together! This looks awesome! I probably will leave more comments later because I still sometimes have trouble remembering what exactly I did in ground software and radio session lol. but for now, I think this looks nearly done

2020-12-17 03:21 UTC, tanishqaggarwal requested changes

2020-12-17 03:21 UTC, tanishqaggarwal commented on ptest/cases/autonomous_mission_manager_case.py
> +            return False
If follower state was standby, then state_check still returns false, so this logic will unnecessarily move the follower state to safehold.

2020-12-17 03:21 UTC, tanishqaggarwal commented on ptest/cases/autonomous_mission_manager_case.py
> +            return False
We should also _actually_ end the mission by writing to the leader/follower mission state.

2020-12-17 03:21 UTC, tanishqaggarwal commented on ptest/cases/autonomous_mission_manager_case.py
> +            return False
This is a piece of logic that we should test on our next autonomous mission manager test. Are there other substantive chunks of logic that you think we should test? Can we make a list

2020-12-17 03:21 UTC, tanishqaggarwal commented on ptest/cases/autonomous_mission_manager_case.py
> +                self.follower.write_state("pan.state", 3)
To make the write successful here, we need to modify the logic in `radio_session` that currently rejects writing states if an `uplink.json` file already exists.

2020-12-17 03:21 UTC, tanishqaggarwal commented on ptest/cases/autonomous_mission_manager_case.py
> +        #TODO exit gracefully if mission ended
For the sake of more carefully tracking all of the work we're doing, should we split these items into separate tickets that are "nice to haves" and reduce the scope of the current issue describing the AMC?

2020-12-17 03:21 UTC, tanishqaggarwal commented on ptest/cases/autonomous_mission_manager_case.py
> +        self.comms_time_threshold = 60*5*1000000000 #currently 5 minutes for testing
```suggestion
        self.comms_time_threshold = 60*5 #currently 5 minutes for testing
```
time.time() returns a float in [seconds](https://docs.python.org/3/library/time.html#time.time)

2020-12-17 03:21 UTC, tanishqaggarwal commented on tlm/email_processor.py
> +        print(self.confirmation_mtmsn, self.mtmsn, self.send_uplinks)
```suggestion
```
Don't want to commit this to master, although we will probably need to have this in be in for a while due to #566

2020-12-17 03:21 UTC, tanishqaggarwal commented on ptest/radio_session.py
> +        print(tlm_service_active, response.text)
```suggestion
```
We resolved the issue that we were trying to get more information about with this print statement; don't need it anymore.

2020-12-17 03:21 UTC, tanishqaggarwal commented on ptest/cases/autonomous_mission_manager_case.py
> +            self.leader.write_multiple_states(baseline_orbit_data_fields, baseline_orbit_data_vals_leader)
Second the last successful comms thing. @fatimayousuf what might be the best way to retrieve the last successful uplink time?

2021-01-07 19:02 UTC, kylekrol commented on ptest/cases/autonomous_mission_manager_case.py
> +            return False
Is this something that we want to be done autonomously though?

2021-01-13 04:49 UTC, afoarce commented on ptest/cases/autonomous_mission_manager_case.py
> +                self.follower.write_state("pan.state", 3)
What would be the best way to update writing states? Should we read and edit an existing json file whenever we need to update a state, or should we change the uplink logic such that radio session maintains a dictionary and only writes the states and fields to a json file when it is time to send the uplink? Or, something else?

2021-01-13 04:52 UTC, afoarce commented on ptest/cases/autonomous_mission_manager_case.py
> +            return False
We should definitely test it both in terms of a satellite faulting and then the next chunk of logic with regards to comms blackouts, which now should also put the satellites in standby. The changes being made to the uplink logic should also be tested to make sure all of the latest state values are being sent.

2021-01-13 04:56 UTC, afoarce commented on ptest/cases/autonomous_mission_manager_case.py
> +            return False
To be more consistent with the logic of either satellites faulting which does change states, I've made it so that both satellites go into standby if comms are down.

2021-01-25 02:57 UTC, shihaocao commented on ptest/cases/autonomous_mission_manager_case.py
> +        leader_time_since_comms = time.time() - self.leader_time_last_comms
This should be last downlink time? Ask how to get those timestamps from elastic search?

2021-01-25 03:24 UTC, shihaocao commented on ptest/cases/autonomous_mission_manager_case.py
> +        self.comms_time_threshold = 60*5 #currently 5 minutes for testing
needs to go after removing boot utility, and should be more easily configurable?

2021-01-25 03:44 UTC, shihaocao commented on ptest/cases/base.py
>      def fast_boot_follower(self):
move to AMC

2021-01-25 03:46 UTC, shihaocao commented on ptest/radio_session.py
> +        if tlm_service_active and response.text.lower()=="true" and not os.path.exists("uplink.json"):
@tanishqaggarwal @afoarce Why did we add this?

2021-01-25 03:52 UTC, shihaocao commented on tlm/email_processor.py
> +        self.send_uplinks=True
@athena255 @tanishqaggarwal Are these changes all vetted?

2021-01-25 03:53 UTC, shihaocao commented on ptest/cases/autonomous_mission_manager_case.py
> +        if(self.mission_conditions_met()):
breakout into subroutine, and make an independent stateless check for whether or not to enable telemetry

2021-01-25 03:54 UTC, shihaocao requested changes
fix per call :) bet

2021-01-30 00:31 UTC, afoarce commented on ptest/cases/autonomous_mission_manager_case.py
> +        leader_time_since_comms = time.time() - self.leader_time_last_comms
Since we really care more about how recent orbit data is, those time stamps should be okay and we could account for longer time to get downlinked to the database by increasing the threshold?

2021-01-30 00:37 UTC, afoarce commented on ptest/cases/autonomous_mission_manager_case.py
> +        if(self.mission_conditions_met()):
Breaking out the logic makes the code messier/redundant since we have different outcomes from different conditions, so I have instead renamed it to continue_mission to avoid confusion of the function implying statelessness

2021-01-31 23:36 UTC, shihaocao commented on ptest/cases/autonomous_mission_manager_case.py
> +        leader_time_since_comms = time.time() - self.leader_time_last_comms
Yeah I think this is fine. `orbit.time` is the time of the data which is probably the only relevantly important time stamp

2021-01-31 23:37 UTC, shihaocao approved these changes
Looks good! Wish we could have a smart read built into usb_session/radio session haha. Maybe a thing for the next PR lol

2021-02-04 17:36 UTC, tanishqaggarwal reviewed
Looks pretty good, just a couple of minor stylistic comments

2021-02-04 17:36 UTC, tanishqaggarwal commented on ptest/cases/autonomous_mission_manager_case.py
> +        return True
```suggestion
    def state_check(self, satellite, designation):
        satellite_state = satellite.read_state("pan.state")
        if(satellite_state == str(Enums.mission_states["standby"])):
            self.logger.put(designation + " is in standby. Ending mission." )
            return False
        elif(satellite_state == str(Enums.mission_states["safehold"])):
            self.logger.put(designation + " is in safehold. Ending mission.")
            return False
        return True
```

2021-02-04 17:36 UTC, tanishqaggarwal commented on ptest/cases/autonomous_mission_manager_case.py
> +                self.follower.write_state("pan_state", Enums.mission_states["safehold"])
Not convinced that this logic works. Let's say the follower state is follower. Then the first if statement (line 24) passes, then the follower's state will be forced into standby unnecessarily.

2021-02-04 17:36 UTC, tanishqaggarwal commented on ptest/cases/autonomous_mission_manager_case.py
> +        self.follower = self.radio_follower if self.using_radios else self.flight_controller_follower
```suggestion
        self.leader = self.radio_leader if self.radio_leader !=None else self.flight_controller_leader
        self.follower = self.radio_follower if self.using_radios else self.flight_controller_follower
```
The `using_radios` variable isn't used anywhere else in the code as far as I can tell, so you could a) get rid of it, b) increase parity between leader and follower initializations.

2021-02-04 17:36 UTC, tanishqaggarwal commented on ptest/cases/autonomous_mission_manager_case.py
> +        leader_time_since_comms = time.time() - self.leader_time_last_comms
I initially got confused by the use of `leader_time_since_comms` and `self.leader_time_last_comms` because they sound similar--on first glance the code seemed to keep rewriting self.leader_time_last_comms. Personally, I feel like it would be clearer just to leave this quantity unnamed inside the if statement on the next line.

2021-02-04 17:36 UTC, tanishqaggarwal commented on ptest/cases/autonomous_mission_manager_case.py
> +        self.follower = self.radio_follower if self.using_radios else self.flight_controller_follower
Also are you guys making the AMC satellite-free? In that case you wouldn't need the radio logic right

2021-02-04 17:36 UTC, tanishqaggarwal commented on tlm/email_processor.py
> +        self.send_uplinks=True
These changes have been working when we tested a while ago...

2021-02-04 17:36 UTC, tanishqaggarwal commented on ptest/radio_session.py
> +        if tlm_service_active and response.text.lower()=="true" and not os.path.exists("uplink.json"):
Discussed offline, the idea was that we don't allow an uplink to be modified by _PTest_ once one has been formed and not yet sent. (It may still be modified by the mission operators through the UplinkTimer.) This way, there is no race condition between PTest/AMC writing to the uplink and the uplink timer actually sending (and destroying) the uplink.

2021-02-04 17:36 UTC, tanishqaggarwal commented on ptest/radio_session.py
> +        if tlm_service_active and response.text.lower()=="true" and not os.path.exists("uplink.json"):
Equivalently (this would be smarter) we could just have a class member containing the uplink and we check if its not None

2021-02-04 17:36 UTC, tanishqaggarwal commented on ptest/radio_session.py
> +        if tlm_service_active and response.text.lower()=="true" and not os.path.exists("uplink.json"):
I think the reason we did it this way though is so that concurrent processes (e.g. uplink timer, etc.) can read/write to the uplink file. Otherwise I think the class member is not visible from another thread (but this may be false)

2021-02-05 17:49 UTC, afoarce commented on ptest/cases/autonomous_mission_manager_case.py
> +                self.follower.write_state("pan_state", Enums.mission_states["safehold"])
What would we want to do instead if the leader is not functional?

2021-02-05 17:53 UTC, afoarce commented on ptest/cases/autonomous_mission_manager_case.py
> +        self.follower = self.radio_follower if self.using_radios else self.flight_controller_follower
I think this wouldn't work because both radios are initialized, but we only have one physical radio to test on which is why the leader is set to the flight_controller automatically. We will eventually have no satellites, but we will still need the radio_session connection to read and send uplinks.

2021-02-06 01:34 UTC, tanishqaggarwal commented on ptest/cases/autonomous_mission_manager_case.py
> +                self.follower.write_state("pan_state", Enums.mission_states["safehold"])
Oh! I missed the if statement for the leader. Thanks

2021-02-06 16:36 UTC, tanishqaggarwal commented on ptest/cases/autonomous_mission_manager_case.py
> +                self.follower.write_state("pan.state", 3)
My original thought behind uplinking was that we shouldn't update any existing json file (or struct) via write_state. Otherwise, there will be a race condition between a writer to the json file and the sending logic (which sends the uplink precisely five minutes after it is created.) The only allowable updates after the initial creation of the packet would be from manual commanding, which can update the uplink up until 1 minute before its sending.

The dictionary thing makes sense from a memory perspective. I think I didn't implement it that way because threading made the data inaccessible to some parts of the program. But that assumption might be incorrect. Feel free to change it if it works

2021-02-06 16:37 UTC, tanishqaggarwal commented on ptest/cases/autonomous_mission_manager_case.py
> +        self.follower = self.radio_follower if self.using_radios else self.flight_controller_follower
Sure, ok. So it's eventually on the docket though to make the AMC satellite-free

2021-02-10 01:48 UTC, merged