Adding state field components
pathfinder-for-autonomous-navigation/FlightSoftware pull request #568
Opened 2020-12-06 22:37 UTC by knk38

# Updating Serializers for ADCS Box Monitor

Fixes #540 
### Summary of changes
- Added a new float serializer for each of the state fields
- Set each new component state field to take data from its respective vector field

### Testing
Since these fields won't be tested by the software unit tests, we may need to change either the testing or this implementation.

### Documentation Evidence
Didnt really need much documentation as this builds from the past state fields

2020-12-06 22:39 UTC, kkrol27 commented
Are `.[xyz]` state field name suffixes going to break things?

2020-12-06 22:40 UTC, knk38 commented
> Are `.[xyz]` state field name suffixes going to break things?

I talked with shihao and the plotter actually automatically combines .[xyz] fields together so it should be compatible, thats why i changed it from the 0,1,2 that i had before

2020-12-08 21:52 UTC, shihaocao commented
@knk38 Actually, haha that's not yet a feature, but I think it'd be a good feature to have along with this PR if we did choose to go to the multiple statefield route instead of a specialized rectangular serailizer

2020-12-17 00:53 UTC, kkrol27 reviewed
I think there are some changes that we need to make to this prior to merging. Also, do we need to update telemetry flows or is that going to happen at a later date?

2020-12-17 00:53 UTC, kkrol27 commented on src/fsw/FCCode/ADCSBoxMonitor.cpp
> +    rwa_speed_rd_component_sr(adcs::rwa::min_speed_read,adcs::rwa::max_speed_read, 8),
Are we looking for full resolution here? If so, then this needs to be 12 bits and not 8 (read is done with a 12 bit ADC and the I2C register is 16 bits):
```suggestion
    rwa_speed_rd_component_sr(adcs::rwa::min_speed_read,adcs::rwa::max_speed_read, 12),
```

2020-12-17 00:53 UTC, kkrol27 commented on src/fsw/FCCode/ADCSBoxMonitor.cpp
> +    rwa_torque_rd_component_sr(adcs::rwa::min_torque,adcs::rwa::max_torque, 8),
Same deal here with the torque read component if we want full resolution:
```suggestion
    rwa_torque_rd_component_sr(adcs::rwa::min_torque,adcs::rwa::max_torque, 12),
```

2020-12-17 00:53 UTC, kkrol27 commented on src/fsw/FCCode/ADCSBoxMonitor.cpp
> +    ssa_vec_sr(-1,1,16*3), //referenced from I2C_Interface.doc
The sun sensor vector is actually supposed to be a unit vector. @tanishqaggarwal not 100% sure what a serializer for that looks like but that's what we need here.

2020-12-17 00:53 UTC, kkrol27 commented on src/fsw/FCCode/ADCSBoxMonitor.cpp
> +    mag1_vec_component_sr(adcs::imu::min_mag1_rd_mag, adcs::imu::max_mag1_rd_mag, 8),
This needs to be a 16 serializer if we want full resolution:
```suggestion
    mag1_vec_component_sr(adcs::imu::min_mag1_rd_mag, adcs::imu::max_mag1_rd_mag, 16),
```

2020-12-17 00:53 UTC, kkrol27 commented on src/fsw/FCCode/ADCSBoxMonitor.cpp
> +    mag2_vec_component_sr(adcs::imu::min_mag2_rd_mag, adcs::imu::max_mag2_rd_mag, 8),
Same thing here if we want full resolution:
```suggestion
    mag2_vec_component_sr(adcs::imu::min_mag2_rd_mag, adcs::imu::max_mag2_rd_mag, 16),
```

2020-12-17 00:53 UTC, kkrol27 commented on src/fsw/FCCode/ADCSBoxMonitor.cpp
> +    gyr_temp_sr(adcs::ssa::min_voltage_rd, adcs::ssa::max_voltage_rd, 16), //referenced from I2C_Interface.doc
Why did we update the bounds for this serializer?

2020-12-17 01:18 UTC, tanishqaggarwal commented on src/fsw/FCCode/ADCSBoxMonitor.cpp
> +    rwa_speed_rd_sr(adcs::rwa::min_speed_read, adcs::rwa::max_speed_read, 16*3), //referenced from I2C_Interface.doc
```suggestion
    rwa_speed_rd_sr(0,0,1), // Dummy serializer, required for rwa_speed_rd to be writable by psim
```

2020-12-17 01:18 UTC, tanishqaggarwal commented on src/fsw/FCCode/ADCSBoxMonitor.cpp
> +    rwa_torque_rd_sr(adcs::rwa::min_torque, adcs::rwa::max_torque, 16*3), //referenced from I2C_Interface.doc
```suggestion
    rwa_torque_rd_sr(adcs::rwa::min_torque, adcs::rwa::max_torque, 16*3), // Dummy serializer, required for rwa_torque_rd to be readable by psim
```

2020-12-17 01:27 UTC, tanishqaggarwal requested changes

2020-12-17 01:27 UTC, tanishqaggarwal commented on src/fsw/FCCode/ADCSBoxMonitor.cpp
> +    ssa_vec_sr(-1,1,16*3), //referenced from I2C_Interface.doc
Tracked to fix this on #539

2020-12-17 01:27 UTC, tanishqaggarwal commented on src/fsw/FCCode/ADCSBoxMonitor.cpp
> +    mag1_vec_sr(adcs::imu::min_mag1_rd_mag, adcs::imu::max_mag1_rd_mag, 16*3), //referenced from I2C_Interface.doc
```suggestion
    mag1_vec_sr(0, 0, 1), // dummy serializer required for magnetic field vector to be writable from psim
```

2020-12-17 01:27 UTC, tanishqaggarwal commented on src/fsw/FCCode/ADCSBoxMonitor.cpp
> +    mag2_vec_sr(adcs::imu::min_mag2_rd_mag, adcs::imu::max_mag2_rd_mag, 16*3), //referenced from I2C_Interface.doc
```suggestion
    mag2_vec_sr(0, 0, 1), // dummy serializer required for magnetic field vector to be writable from psim
```

2020-12-17 01:27 UTC, tanishqaggarwal commented on src/fsw/FCCode/ADCSBoxMonitor.cpp
> +    gyr_vec_sr(adcs::imu::min_rd_omega, adcs::imu::max_rd_omega, 16*3), //referenced from I2C_Interface.doc
```suggestion
    gyr_vec_sr(0, 0, 1), // dummy serializer required for gyroscope reading to be writable from psim
```

2020-12-17 01:29 UTC, shihaocao commented on src/fsw/FCCode/ADCSBoxMonitor.cpp
> +    gyr_temp_sr(adcs::ssa::min_voltage_rd, adcs::ssa::max_voltage_rd, 16), //referenced from I2C_Interface.doc
gyr_temp_sr(adcs::imu::min_rd_temp, adcs::imu::max_rd_temp, 8), //full res is 16

is appropriate

2020-12-17 01:30 UTC, kkrol27 commented on src/fsw/FCCode/ADCSBoxMonitor.cpp
> +    gyr_temp_sr(adcs::ssa::min_voltage_rd, adcs::ssa::max_voltage_rd, 16), //referenced from I2C_Interface.doc
```suggestion
    gyr_temp_sr(adcs::imu::min_rd_temp, adcs::imu::max_rd_temp, 8),
```

2020-12-17 01:51 UTC, tanishqaggarwal commented on src/fsw/FCCode/ADCSBoxMonitor.cpp
> +    ssa_vec_sr(-1,1,16*3), //referenced from I2C_Interface.doc
```suggestion
    ssa_vec_sr(0,1,1), // Dummy serializer, needs to get fixed in #539 
```

2020-12-17 02:02 UTC, shihaocao commented on src/fsw/FCCode/ADCSBoxMonitor.cpp
> +    ssa_vec_sr(-1,1,16*3), //referenced from I2C_Interface.doc
```suggestion
    ssa_vec_sr(0,1,1 + SerializerConstants::min_fvsz),
```

2020-12-17 02:02 UTC, shihaocao commented on src/fsw/FCCode/ADCSBoxMonitor.cpp
> +    ssa_vec_sr(-1,1,16*3), //referenced from I2C_Interface.doc
revert to master

2020-12-17 02:04 UTC, shihaocao commented on src/fsw/FCCode/ADCSBoxMonitor.cpp
> +    ssa_voltage_sr(adcs::ssa::min_voltage_rd, adcs::ssa::max_voltage_rd, 8),
unsigned char in pass thru anyway

2020-12-17 02:13 UTC, shihaocao commented on src/fsw/FCCode/ADCSBoxMonitor.cpp
> +    gyr_temp_sr(adcs::ssa::min_voltage_rd, adcs::ssa::max_voltage_rd, 16), //referenced from I2C_Interface.doc
This shall be restored back to master version with 16 bit res

2020-12-17 02:14 UTC, shihaocao commented on src/fsw/FCCode/ADCSBoxMonitor.cpp
> +    gyr_temp_sr(adcs::imu::min_rd_temp, adcs::imu::max_rd_temp, 16), //full res is 16
bump to full res for consistency

2020-12-17 02:29 UTC, tanishqaggarwal approved these changes

2020-12-17 02:33 UTC, kkrol27 approved these changes

2020-12-17 02:44 UTC, merged