PSim Configuration in PTest
pathfinder-for-autonomous-navigation/FlightSoftware pull request #603
Opened 2020-12-25 21:42 UTC by shihaocao

# PSim Configuration in PTest

Complementary PR to PSim PR:
https://github.com/pathfinder-for-autonomous-navigation/psim/pull/285

### Summary of changes
- Added new property: sim_ic_map, a dictionary with psim state field names as strings, and values as initial conditions to overwrite
- Updated PTest simulation backend to support

### Testing
Tested on PsimDebug

### Constants
N/A

### Telemetry
N/A

2020-12-25 21:45 UTC, tanishqaggarwal requested changes

2020-12-25 21:45 UTC, tanishqaggarwal commented on ptest/cases/base.py
> +            stripped = str(ret).strip("[]").replace(" ","")+","
What is this doing?

2020-12-25 21:45 UTC, tanishqaggarwal commented on ptest/psim/simulation.py
> +from ..cases.utils import to_lin_vector
```suggestion
from ..cases.utils import is_lin_vector, to_lin_vector
```

2020-12-25 21:49 UTC, shihaocao commented on ptest/cases/base.py
> +            stripped = str(ret).strip("[]").replace(" ","")+","
This is actually a bug fix that prevented int fields from being plotted

2020-12-25 21:50 UTC, shihaocao commented on ptest/cases/base.py
> +            stripped = str(ret).strip("[]").replace(" ","")+","
Now psim int fields can be plotted in ptest

2020-12-25 21:50 UTC, tanishqaggarwal approved these changes

2020-12-25 23:04 UTC, kylekrol approved these changes
Seems good to me! Only thing that I wonder is if making a callback function that gives PSim related testcases a chance to operate directly on the `config` may be easier that using a dictionary passed down by a property.

That's just a suggesting, not at all a request, so going ahead and approving.

2020-12-25 23:05 UTC, kylekrol commented
@shihaocao forgot we need to bump the psim pointer again but yeah after that everything looks good!

2020-12-25 23:20 UTC, shihaocao commented
> @shihaocao forgot we need to bump the psim pointer again but yeah after that everything looks good! Perhaps add the psim debug case to CI as well?

Lol PsimDebug has just been this running testcase for me to check the functionality of each new feature I add, and was never really meant to be a staple ci case... Could def make it one tho

I'll consider it on the next PR where I delete ci.txt, and actually use this infrastructure for faster detumbling

2020-12-25 23:32 UTC, merged

2020-12-26 17:02 UTC, kylekrol commented
> > @shihaocao forgot we need to bump the psim pointer again but yeah after that everything looks good! Perhaps add the psim debug case to CI as well?
> 
> Lol PsimDebug has just been this running testcase for me to check the functionality of each new feature I add, and was never really meant to be a staple ci case... Could def make it one tho
> 
> I'll consider it on the next PR where I delete ci.txt, and actually use this infrastructure for the detumble ci case
> @kylekrol

Sounds good. But yeah was just thinking it may be good to get some of this going in CI to make sure bumping the psim pointer won't ever break some of this basic functionality.