Prop fault response ptest
pathfinder-for-autonomous-navigation/FlightSoftware pull request #609
Opened 2021-01-05 20:25 UTC by athena255

# PropFaultHandler Ptest Case

### Summary of changes
- `prop_fault_handler.py` rewritten to have tests based on faked sensor values
- `requirements.txt` modified to support Python 3.9
-`Fault.cpp` modified `signal()` to set the faulted state when `num_consecutive_signals` exceeds persistence
- `MainFaultHandler.cpp` added PropFaultHandler to `fault_handler_machines`
- `MissionManager.cpp` modified to prevent transitioning prop to idle
- `PropController.cpp::execute()` check_faults() now occurs at the start of execution instead of at the end of execution. This is to allow the ptest to cause faults by setting fake sensor values after the call to `cycle()`
- `PropController.cpp::check_faults(), can_enter()` modified to make sure that all faults call `is_faulted()` since the prior implementation had the calls in a boolean expression, which was short-circuited resulting in one-cycle delays when evaluating faults that should be triggered in the same cycle
- `PropController.hpp` functions for checking whether sensors exceed max safe value have been modified to use `>` instead of `>=` 
- `PropFaultHandler.cpp` changes to cast prop state to unsigned int instead of unsigned char
- `PropFaultHandler.h` removed `pressurize_fail_fault` since PFH does not do anything with his fault
- `test_main_fault_handler.cpp` modified to reflect changes to MissionManager
- `test_mission_manager.cpp` modified to reflect changes to MissionManager
- `test_prop_controller.cpp` added tests for venting both tanks
- `test_prop_faults.cpp` modified to reflect one cycle delay due to checking for faults at the beginning of PropController execution, also added tests for resolving overpressured fault by suppressing

### Significant Bug Fixes
-Previously, PropFaultHandler would recommend a standby when Prop was in handling_fault or venting. However, this causes the MissionManager to transition the prop state machine to idle. This resulted in a one cycle delay in handling_fault
- Because Fault.cpp previously requires a call to is_faulted() to actually set the fault state and PropController used the boolean `||` to compare fault states, this caused the evaluation to short-circuit, which made the detection of faults one cycle late when multiple faults are signaled at the same time  

### Significant Behavior Changes
- The` prop_state_t::disabled` prevents the prop from venting. MissionManager was modified to not transition the prop to disabled once the prop has been turned on
- MissionManager no longer transition prop state to idle when the recommended fault response is standby or safehold. This fixes a one-cycle delay bug that occured when venting
- MissionManager.cpp now commands prop into idle during detumbling. The concern was that detumbling has the potential to cause pressure/temperature changes in the prop tank. This behavior change results in the dcdc spike and doc pin being set earlier
- `signal()` now sets the fault state when `num_consecutive_signals` exceeds persistence. Previously, the fault state was only evaluated upon calling is_faulted() 
- Since PropController now calls `check_faults()` at the beginning of execution, faults are detected by PropFaultHandler one cycle late

### TODO
- OrbitController should only schedule firings when it is in follower

### Constants
- N/A

### Telemetry
- N/A

2021-01-07 00:37 UTC, shihaocao commented on src/fsw/FCCode/PropController.cpp
> +           b_tank1_temp);
to prevent short circuit eval

2021-01-08 01:36 UTC, athena255 commented on ptest/cases/prop_state_machine_case.py
> +        return (int(self.ctrl_cycles_per_filling) + int(self.ctrl_cycles_per_cooling))*int(self.max_pressurizing_cycles) + 4 + int(self.ctrl_cycles_per_filling)
modified to account for Prop State Machine change which requires waiting in Await_Pressurizing for 1 second in which DCDC pin is high.

2021-01-08 01:36 UTC, athena255 commented on ptest/cases/prop_state_machine_case.py
> -        self.flight_controller.write_state("dcdc.SpikeDock_cmd", True)
Since prop sets this itself now, we do not need to set this anymore

2021-01-08 01:37 UTC, athena255 commented on ptest/cases/prop_state_machine_case.py
> +        if not self.read_state("dcdc.SpikeDock_cmd") == "true":
Prop should set this right after it receives a valid schedule

2021-01-08 01:37 UTC, athena255 commented on ptest/cases/prop_state_machine_case.py
> +        if not self.read_state("dcdc.SpikeDock_cmd") == "false":
Prop should unset DCDC on transition to idle

2021-01-08 01:38 UTC, athena255 commented on src/common/Fault.cpp
> +    if (num_consecutive_signals > persistence_f.get()) {
signal() should set the fault upon detecting that num_consecutive_signals exceeds persistence

2021-01-08 01:38 UTC, athena255 commented on src/fsw/FCCode/MissionManager.cpp
> -
MissionManager no longer needs dcdc.SpikeDoc_cmd since prop sets it itself

2021-01-08 01:39 UTC, athena255 commented on src/fsw/FCCode/MissionManager.cpp
> -    if (prop_state == prop_state_t::disabled && mission_state != mission_state_t::docking)
MissionManager no longer sets SpikeHold DCDC

2021-01-08 01:40 UTC, athena255 commented on src/fsw/FCCode/OrbitController.cpp
> +           4 + ctrl_cycles_per_filling_period_fp->get();
The min_num_cycles to set for cycles_until_firing has been increased by 1 second (`ctrl_cycles_per_filling_period`) to require that AwaitPressurizing reads DCDC SpikeDock high for ~1 second

2021-01-08 01:41 UTC, athena255 commented on src/fsw/FCCode/PropController.cpp
> +    check_faults();
Faults are checked at the beginning of the cycle to enable ptest cases, which cause faults by faking sensor values

2021-01-08 01:41 UTC, athena255 commented on src/fsw/FCCode/PropController.cpp
> +    // Do not check_faults when we are disabled
Faults are no longer checked when the prop is in disabled

2021-01-08 01:43 UTC, athena255 commented on src/fsw/FCCode/PropController.cpp
> +
Set SpikeHold DCDC upon detecting potential venting conditions. 
Warning: there is no code to unset this until prop naturally transitions to idle

2021-01-08 01:44 UTC, athena255 commented on src/fsw/FCCode/PropController.cpp
> +unsigned int PropController::min_cycles_pressurizing_only() const
This is the old value of min_cycles_needed().

2021-01-08 01:44 UTC, athena255 commented on src/fsw/FCCode/PropController.cpp
> +}
Modified to account for the 1s in Await_Pressurizing where DCDC SpikeHold pin must be high

2021-01-08 01:44 UTC, athena255 commented on src/fsw/FCCode/PropController.cpp
> +    controller->sph_dcdc_fp->set(false);
Set SpikeHold DCDC to false upon entering disabled

2021-01-08 01:45 UTC, athena255 commented on src/fsw/FCCode/PropController.cpp
>      return true;
We can always enter idle

2021-01-08 01:45 UTC, athena255 commented on src/fsw/FCCode/PropController.cpp
> +    controller->sph_dcdc_fp->set(false);
Sets SpikeHold DCDC to false upon entering Idle

2021-01-08 01:46 UTC, athena255 commented on src/fsw/FCCode/PropController.cpp
> +    // Enter Await Pressurizing if schedule is valid and we have enough time
Modified because prop no longer allows transitioning directly into Pressurizing.

2021-01-08 01:47 UTC, athena255 commented on src/fsw/FCCode/PropController.cpp
> +    controller->sph_dcdc_fp->set(true);
SpikeHold DCDC pin is set to true upon entering AwaitPressurizing

2021-01-08 01:48 UTC, athena255 commented on src/fsw/FCCode/PropController.cpp
> +    if (PropulsionSystem.is_functional())
Require that we digitalRead the actual SpikeHold pin as HIGH consecutively for ~1 second before allowing Prop to go into Pressurizing.

2021-01-08 01:49 UTC, athena255 commented on src/fsw/FCCode/PropController.cpp
> +    if (controller->cycles_until_firing.get() < controller->min_cycles_pressurizing_only() - 1)
Have the prop return to idle when it realizes that it could not possibly fire on time

2021-01-08 01:50 UTC, athena255 commented on src/fsw/FCCode/PropController.cpp
> +    if (n_cycles_dcdc_high < controller->ctrl_cycles_per_filling_period.get())
Prevent prop from going into Pressurizing if it has not seen DCDC high consecutively for 1 second

2021-01-08 01:50 UTC, athena255 commented on src/fsw/FCCode/PropController.cpp
> -    // Allow from idle because sometimes we can immediately pressurize
Do not allow entering this state from idle

2021-01-08 01:51 UTC, athena255 commented on src/fsw/FCCode/PropController.cpp
> +    bool b_pressurize_fail = controller->pressurize_fail_fault_f.is_faulted();
Modified to avoid short circuit evaluation of is_faulted()

2021-01-08 01:52 UTC, athena255 commented on src/fsw/FCCode/PropController.hpp
> +        return tank2_pressure_f.get() > max_safe_pressure;
tank2 is overpressured only if it exceeds max_safe_pressure rather than if it is at max_safe_pressure (assuming that being at max_safe_pressure is ok)

2021-01-08 01:53 UTC, athena255 commented on test/test_fsw_orbit_controller/test_orbit_controller.cpp
> +                // Prop needs this
Create this statefield because Prop expects it.

2021-01-08 01:54 UTC, athena255 commented on test/test_fsw_prop_controller/prop_shared.h
> +    inline fault_response_t step(size_t num = 1)
Modified to return the fault_response_t recommended by prop fault handler

2021-01-08 01:54 UTC, athena255 commented on test/test_fsw_prop_controller/test_prop_controller.cpp
> -// Test that a schedule with fire_cycle set to prop_controller->min_cycles_needed() and all valve
No more idle to pressurizing

2021-01-08 01:55 UTC, athena255 commented on test/test_fsw_prop_controller/test_prop_controller.cpp
> -void test_idle_to_await_pressurize_helper(bool functional = true)
Since prop sets DCDC SpikeHold pin, we do not need to test the case where the pin is not already set

2021-01-08 01:56 UTC, athena255 commented on test/test_fsw_prop_controller/test_prop_controller.cpp
> +void test_vent_both_tanks()
Added tests to verify the changed Prop State Machine behaviors

2021-01-08 01:56 UTC, athena255 commented on test/test_fsw_prop_controller/test_prop_controller.cpp
> +    RUN_TEST(test_not_enough_cycles_for_dcdc_high);
Called multiple times since previously, some of these tests failed when they were called a second time.

2021-01-08 01:57 UTC, athena255 commented on test/test_fsw_prop_faults/test_prop_faults.cpp
> +    tf.step(get_persistence(overpressure_fault_f) + 2);
Faults are no longer detected if prop is in disabled

2021-01-08 01:57 UTC, athena255 commented on test/test_fsw_prop_faults/test_prop_faults.cpp
> +    tf.step(get_persistence(tank1_temp_high_fault_f) + 2);
Fault is detected a cycle late because check_faults() now occurs at the beginning of the cycle.

2021-01-08 01:58 UTC, athena255 commented on test/test_fsw_prop_faults/test_prop_faults.cpp
> +void test_underpressured_unsignal_response()
Added test for more realistic response to underpressured event. (The ground is expected to unsignal the fault and then lower the threshold pressure)

2021-01-13 22:18 UTC, shihaocao commented on src/fsw/FCCode/PropController.cpp
> +        n_cycles_dcdc_high = 0; // reset this just in case
what's this for?

2021-01-13 22:24 UTC, shihaocao commented on src/fsw/FCCode/MainFaultHandler.cpp
> +    fault_handler_machines.push_back(std::make_unique<PropFaultHandler>(_registry));
How does this change interface with line 26 of this file? In other words do we need to remove line 26?

2021-01-13 22:27 UTC, shihaocao commented on src/fsw/FCCode/MissionManager.cpp
> +                      prop_state_t::idle);
The only time we derail the state machine. If we are handling a fault (like venting and stuff) when transitioning from some other startup to detumble though (which is a small chance), it would appear as if we could potentially mess up the state machine?

I am okay with this small probability though

2021-01-13 22:27 UTC, shihaocao commented on src/fsw/FCCode/OrbitController.cpp
> +           4 + ctrl_cycles_per_filling_period_fp->get();
Where is the setting that actually defines this ~1 second wait

2021-01-13 22:28 UTC, shihaocao commented on src/fsw/FCCode/OrbitController.cpp
> +           4 + ctrl_cycles_per_filling_period_fp->get();
oh i see it in the constants now

2021-01-13 22:29 UTC, shihaocao commented on src/fsw/FCCode/PropController.cpp
>              prop_state_f.set(static_cast<unsigned int>(prop_state_t::disabled));
Do we ever expect this to happen if all hardware is performing nonmially?
If not, could we tag this with an "[ ERROR ]"?

2021-01-13 22:30 UTC, shihaocao commented on src/fsw/FCCode/PropController.cpp
>              prop_state_f.set(static_cast<unsigned int>(prop_state_t::disabled));
on the debug print out that is

2021-01-13 22:30 UTC, shihaocao commented on src/fsw/FCCode/PropController.cpp
> +    // Do not check_faults when we are disabled
Why? Is it possible to still have faults checked, but just have them not let us leave disabled?

2021-01-13 22:32 UTC, shihaocao commented on src/fsw/FCCode/PropController.cpp
> +
Seems good to me

If a ground command simultaneously suppressed all faults, set prop state to idle, and set dcdc off, it should be as if it were in a normal idle state though right?

2021-01-13 22:32 UTC, shihaocao commented on src/fsw/FCCode/PropController.cpp
> +unsigned int PropController::min_cycles_pressurizing_only() const
What's the 4 about again?

2021-01-13 22:33 UTC, shihaocao commented on src/fsw/FCCode/PropController.cpp
> +}
The above code looks unmodified?

2021-01-13 22:37 UTC, shihaocao commented on src/fsw/FCCode/PropFaultHandler.cpp
> -    pressurize_fail_fault_fp = find_fault("prop.pressurize_fail.base", __FILE__, __LINE__);
curious as to why prop_pressurize_fail is not in here?

2021-01-13 22:42 UTC, shihaocao reviewed
Got a bunch of questions, but otherwise, looking good.

2021-01-14 20:20 UTC, athena255 commented on src/fsw/FCCode/PropController.cpp
> +    // Do not check_faults when we are disabled
We could, but I think we decided that prop should not check faults while in disabled since there's nothing it could do about it anyway

2021-01-14 20:20 UTC, athena255 commented on src/fsw/FCCode/PropController.cpp
> +
yes

2021-01-14 20:22 UTC, athena255 commented on src/fsw/FCCode/PropController.cpp
> +unsigned int PropController::min_cycles_pressurizing_only() const
The min_cycles_needed is the minimum number of cycles until we can fire. That means after min_cycles_needed, we should be in firing. There's an offset of four cycles due to the state transitions: 
idle: schedule is set
1. idle -> await_press: upon detecting valid schedule
2. await_pres -> pres: 
3. pres -> await_firing
4. await_firing->firing

2021-01-14 20:24 UTC, athena255 commented on src/fsw/FCCode/PropController.cpp
> +}
Mb, I meant to put this comment on the next line where min_cycles_needed was modified

2021-01-14 20:27 UTC, athena255 commented on src/fsw/FCCode/PropController.cpp
> +        n_cycles_dcdc_high = 0; // reset this just in case
The n_cycles_dcdc_high is the variable to count the number of cycles in which dcdc was digitalRead to be HIGH. We reset this when we enter pressurizing since this variable only matters in await_pressurizing. This is not truly necessary here since the Await_Pressurizing::can_enter() method resets this anyway, but I set this to 0 just in case .

2021-01-14 20:28 UTC, athena255 commented on src/fsw/FCCode/MainFaultHandler.cpp
> +    fault_handler_machines.push_back(std::make_unique<PropFaultHandler>(_registry));
Line 26 for me is: `find_fault("adcs_monitor.wheel_pot_fault.base", __FILE__, __LINE__)`

2021-01-14 20:29 UTC, athena255 commented on src/fsw/FCCode/MissionManager.cpp
> +                      prop_state_t::idle);
We never truly mess up the state machine. If prop is transitioned to idle when it wants to be in venting, it will immediately transition itself to handling_fault and then to venting again. The machine would only truly be disabled if it was constantly commanded into idle. Worst case scenario would be that venting is two cycle delayed every time it's forced into idle.

2021-01-14 20:31 UTC, athena255 commented on src/fsw/FCCode/PropController.cpp
>              prop_state_f.set(static_cast<unsigned int>(prop_state_t::disabled));
This case actually tends to happen when the dcdc is switched off while the prop needed it. For example, if prop was in Await_Firing, it would attempt to transition to Firing when it's time to fire. But since Firing requires that the dcdc be on, it will fail to transition and go into disabled. The test cases for powerloss that I added in this pr should demonstrate this behavior (i believe).

2021-01-14 20:32 UTC, athena255 commented on src/fsw/FCCode/PropFaultHandler.cpp
> -    pressurize_fail_fault_fp = find_fault("prop.pressurize_fail.base", __FILE__, __LINE__);
Because PropFaultHandler does not do anything with pressurize_fail. If we fail to pressurize, we go into handling fault until the ground does something about it.

2021-01-15 06:56 UTC, shihaocao commented on src/fsw/FCCode/PropController.cpp
> +    // Do not check_faults when we are disabled
I think we should still check faults, that way we can still query these faults to get diagnostic data for the spacecraft

2021-01-15 07:00 UTC, shihaocao commented on src/fsw/FCCode/MainFaultHandler.cpp
> +    fault_handler_machines.push_back(std::make_unique<PropFaultHandler>(_registry));
Oops meant line 30, `find_fault("prop.pressurize_fail.base", __FILE__, __LINE__),`

My question is like, should that fail pressurize fault still there? Is this like double counted?

2021-01-15 07:01 UTC, shihaocao commented on src/fsw/FCCode/MissionManager.cpp
> +                      prop_state_t::idle);
Ah bet

2021-01-15 07:03 UTC, shihaocao commented on src/fsw/FCCode/PropController.cpp
>              prop_state_f.set(static_cast<unsigned int>(prop_state_t::disabled));
Gotcha. I guess my question is like, it would only be the case that DCDC is off when we needed it to be on if our code was bugged, or if the hardware was not acting like we expected to right?

In other words, if we see this message, we need to do bug hunting before launch? (I think the answer is yes)?

2021-01-15 07:04 UTC, shihaocao commented on src/fsw/FCCode/PropFaultHandler.cpp
> -    pressurize_fail_fault_fp = find_fault("prop.pressurize_fail.base", __FILE__, __LINE__);
Ah I see

2021-01-15 07:05 UTC, shihaocao commented on src/fsw/FCCode/MainFaultHandler.cpp
> +    fault_handler_machines.push_back(std::make_unique<PropFaultHandler>(_registry));
I think my own answer to this is, yes we should still have line 30 because that allows us to ask the mission manager to go to standby if we can't pressurize the tanks

Thus nothing is double-counted, and this line change is good too.

2021-01-15 19:07 UTC, athena255 commented on src/fsw/FCCode/PropController.cpp
>              prop_state_f.set(static_cast<unsigned int>(prop_state_t::disabled));
We would only see this message in power loss, but yea, this check is essentially a sanity check.

2021-01-20 23:06 UTC, shihaocao commented on test/test_fsw_mission_manager/test_mission_manager.cpp
> +    // TODO
Todo flags?

2021-01-20 23:06 UTC, shihaocao commented on test/test_fsw_mission_manager/test_mission_manager.cpp
> +    tf.check_sph_dcdc_on(true);
has the todo on line 36 been resolved?

2021-01-21 00:20 UTC, shihaocao requested changes
We should set prop to disabled and dcdc to off if we're in safehold, and to go back to any kind of normal mode from safehold, the ground will be responsible for re-enabling the DCDC and setting prop to idle

2021-01-27 21:25 UTC, athena255 commented on test/test_fsw_mission_manager/test_mission_manager.cpp
> +    // TODO
The TODO was to note that the check_sph_dcdc_on calls are redundant since we manually set dcdc at the beginning of the test case anyway.

2021-01-27 21:43 UTC, athena255 commented
> We should set prop to disabled and dcdc to off if we're in safehold, and to go back to any kind of normal mode from safehold, the ground will be responsible for re-enabling the DCDC and setting prop to idle

What about the case where ground forgets to re-enable the DCDC and the subsystems that require DCDC start reporting faults? It may be safer to do the re-enable in software. That will be one less statefield in the packet and will not require ground (students) to remember to re-enable DCDC. 

Do you think we should put this feature in a different PR?

2021-02-02 21:53 UTC, shihaocao approved these changes
Bet. Thanks for grinding so hard on this

2021-02-02 21:55 UTC, tanishqaggarwal commented
I haven't really been able to keep up with the complex discussion on this PR, so please don't wait for my approval before merging

2021-02-03 03:08 UTC, merged