Add while loop to gomspace controller
pathfinder-for-autonomous-navigation/FlightSoftware pull request #623
Opened 2021-02-04 19:35 UTC by shihaocao

# Add while loop to gomspace controller

Fixes:
- Testing shows that reboots only seem to work once
- The above in part occurs because the flight computer remains on despite having the Gomspace reboot

### Summary of changes
- Add a dead end while loop

### Testing
Tested on 02/04: POC Shihao Cao

2021-02-04 19:53 UTC, kylekrol requested changes
Changes look good to me; although, it seems that we need to run some unit tests locally to fix CI. I'm sure we broke a couple HOOTL, HITL, and unit tests.

2021-02-06 02:53 UTC, kylekrol commented on src/fsw/FCCode/GomspaceController.hpp
> +TRACKED_CONSTANT_SC(unsigned char, default_ppt_mode, 1);
Wooo!

2021-02-06 16:39 UTC, shihaocao commented
Athena pointed out that if we went into this while loop while the inner tank was venting to the outer tank, we'd definitely overpressurize and explode. 

She suggested that instead of using a while loop, we just implement a "mute" on GomSpace behavior

2021-02-06 17:33 UTC, kylekrol commented
Ah okay fair enough. So something like if the reboot flag is true then the GOMSpace control task just doesn't execute any code?

2021-02-09 21:24 UTC, shihaocao commented on src/fsw/FCCode/GomspaceController.cpp
> +        return;
doing it this way still allows other control tasks to attempt to continue working, notably, PropSystem still maintains the ability to close the intertank valve.

2021-02-10 22:23 UTC, shihaocao commented on src/fsw/FCCode/GomspaceController.cpp
> -        ppt_mode_cmd_f.set(gs.hk->pptmode);
removing this, so that FlightSoftware still has authority to set a default

2021-02-11 02:46 UTC, shihaocao commented
I removed the reboot loop because the reset command fully resets the spacecraft. Thus we should just not use the reboot command, and only the reset command.

2021-02-12 03:35 UTC, fatimayousuf approved these changes

2021-02-12 15:06 UTC, kylekrol approved these changes

2021-02-12 19:55 UTC, merged