Piksi Interrupt
pathfinder-for-autonomous-navigation/FlightSoftware pull request #641
Opened 2021-02-21 19:45 UTC by madeleinemc

- intervaltimer for interrupt timestamp
- if bytes increase, update timestamp
- in piksi driver
- add getter to piksi driver to get sendtime
- Added fxns to Piksi driver. Logic to calculate microdelta from sendtime is still in PiksiControlTask

2021-02-23 14:06 UTC, kylekrol commented on src/fsw/FCCode/Drivers/Piksi.cpp
>  #endif
Shouldn't this be something like:
```suggestion
#ifndef DESKTOP
#include <Arduino.h>
#else
// The below are declared in Arduino.h
static void interrupts() {}
static void noInterrupts() {}
#endif
```

2021-02-23 14:09 UTC, kylekrol commented on src/fsw/FCCode/Drivers/Piksi.cpp
> +    }
Apologies if I'm jumping on this PR too early, but an `int` takes up (generally) four bytes in memory and `Serial4.read()` only returns single bytes. We'll want our buffer to be of type `unsigned char buffer[bytes]` to keep the memory continguous.

2021-02-23 14:11 UTC, kylekrol commented on src/fsw/FCCode/Drivers/PropulsionSystem.cpp
> +    past_bytes = bytes;
This seems like it's not supposed to be here?

2021-02-23 16:23 UTC, kylekrol commented on src/fsw/FCCode/Drivers/Piksi.cpp
>      HardwareSerial &sp = piksi->_serial_port;
We can just go ahead and delete this function - either that or replace the function body with the new implementation (latter is probably easier so you don't have to go and find every `_uart_read` and change it).

2021-02-23 18:39 UTC, kylekrol commented
Also the telemetry file is deleted and that doesn't seem right...?

2021-02-25 23:02 UTC, madeleinemc commented on src/fsw/FCCode/Drivers/PropulsionSystem.cpp
> +    past_bytes = bytes;
oh god

2021-02-27 22:06 UTC, kylekrol commented on src/fsw/FCCode/Drivers/Piksi.cpp
> +
```suggestion
```

2021-02-28 04:49 UTC, kylekrol commented on src/fsw/FCCode/Drivers/Piksi.cpp
> +}
Just noting here that we have the potential to overflow an unsigned integer here. Now this was an issue with the `micros()` timer before but now we actually have the opportunity to fix it. Setting the interrupt count back to zero when we used to rewrite start time could help avoid this issue. Something like this:
```suggestion
static volatile int last_bytes = 0;
static volatile unsigned long interrupt_count = 0;
static volatile unsigned long last_interrupt_count;

void Piksi::check_bytes(){
#ifndef DESKTOP
    interrupt_count++;
    int bytes = Serial4.available();
    unsigned long count = interrupt_count;

    // if bytes are entering the buffer, update the timestamp
    if (bytes > last_bytes) {
        if (++interrupt_count - last_time > 100) {
            interrupt_count = 0;
        }

        last_bytes = bytes;
        last_interrupt_count = interrupt_count;
   }
#endif
}

```
We'd then have to update I think the calculation of `piksi.microdelta` at little bit as well. This way though we'd be completely guarded against overflows and we could even move back to `unsigned int` types to make the serializer's happy again!

2021-02-28 04:52 UTC, kylekrol commented on src/fsw/FCCode/Drivers/Piksi.cpp
> +    interrupts();
Also, now because the timing is strictly tied to the interrupt schedule I _think_ we should actually get rid of the timing code here. Like it doesn't allow us to gain a better estimate of the time the messages arrived so we may as well just leave it be other than the `last_bytes` value if that makes sense:
```suggestion
    noInterrupts();

    int bytes = Serial4.available();
    last_bytes = 0;

    buffer_begin = buffer;
    buffer_end = buffer;
    // copy buffer up to available
    for (int i = 0; i < bytes; i++){
        *(buffer_end++) = Serial4.read();
    }
    clear_bytes();

    microdelta = interrupt_count*100; //convert to us

    interrupts();

```
Also, with the small booking keeping change in the ISR, I think we can define the ` microdelta` just based on the interrupt count.

2021-02-28 04:53 UTC, kylekrol commented on src/fsw/FCCode/Drivers/Piksi.cpp
> +    clear_bytes();
Also, just curious like what's goin on with this function here? Shouldn't the buffer already be clear? Wouldn't this only potentially wipe bytes we don't want to wipe?

2021-02-28 04:56 UTC, kylekrol requested changes
We should really take the code time stamping the the main execute loop because it can't really do anything - like whatever it sets the timestamp to is just going to be what the interrupt set it to a tiny bit ago. Also not really sure what the `clear_bytes()` is doing/if it needs to be there?

If you feel like making the other book keeping changes go for it! Otherwise if it works it works haha

2021-03-03 14:06 UTC, kylekrol commented on src/fsw/FCCode/Drivers/Piksi.cpp
> +    last_bytes = 0;
Sorry I didn't notice this the first time but I think we should set `bytes` to the `last_bytes` seen by the interrupt. Otherwise, we could see data passed in between the interrupt and the start of this function call that doesn't get timestamped. It could also mess up timing for the next packet I think.
```suggestion
    int bytes = last_bytes;
    last_bytes = 0;
```

2021-03-03 14:06 UTC, kylekrol commented on src/fsw/FCCode/Drivers/Piksi.cpp
>          }
Should we make this or equals @shihaocao? Unfamiliar with how Piksi works but it seems safer...
```suggestion
        bool crc_error = false;
        while(buffer_begin < buffer_end){
            crc_error |= process_buffer() < 0;
        }

```

2021-03-03 14:06 UTC, kylekrol commented on src/fsw/FCCode/PiksiControlTask.cpp
> +    baseline_pos_f("piksi.baseline_pos", Serializer<d_vector_t>(0,100000,100)),
I don't think we want to change these serializer values here! Pretty sure @tanishqaggarwal set these to very specific values! Did we mean to do this or did things just get lost in the shuffle while merging?

2021-03-04 00:33 UTC, madeleinemc commented on src/fsw/FCCode/PiksiControlTask.cpp
> +    baseline_pos_f("piksi.baseline_pos", Serializer<d_vector_t>(0,100000,100)),
I see! I don't remember changing the values, and the changes don't make much sense to me, so I'll switch it back

2021-03-04 00:35 UTC, shihaocao commented on src/fsw/FCCode/Drivers/Piksi.cpp
>          }
I think `|=` is the safer option because if any particular message has a crc_error, its probably safer to toss the whole read out.

2021-03-04 00:36 UTC, shihaocao commented on src/fsw/FCCode/Drivers/Piksi.cpp
> +    clear_bytes();
@madeleinemc , can we take out the `clear_bytes()` command and see if things still work?

2021-03-04 00:46 UTC, madeleinemc commented on src/fsw/FCCode/Drivers/Piksi.cpp
>          }
src/fsw/FCCode/Drivers/Piksi.cpp:336:46: error: 'crc_error' may be used uninitialized in this function [-Werror=maybe-uninitialized]
             crc_error |= process_buffer() < 0;

2021-03-04 01:11 UTC, kylekrol approved these changes
Looks good to me - this is very exciting to have all wrapped up!

2021-03-04 04:39 UTC, shihaocao commented on src/fsw/FCCode/Drivers/Piksi.cpp
> +// edit this
remove comment

2021-03-04 04:39 UTC, shihaocao commented on src/fsw/FCCode/Drivers/Piksi.hpp
> +#include <Arduino.h>
is this necessary?

2021-03-04 04:48 UTC, shihaocao commented on src/fsw/FCCode/Drivers/Piksi.hpp
> +
Change these to /** doc string comments?

2021-03-04 04:56 UTC, shihaocao commented on src/fsw/FCCode/PiksiControlTask.cpp
> +    no_bytes_available_f("piksi.bytes_available")
what's this field for? I don't think we're using it? We should remove it

2021-03-04 04:56 UTC, shihaocao requested changes
All the microdelta stuff looks good to me. Just a few cosmetic changes to make this production-ready.

2021-03-04 06:26 UTC, tanishqaggarwal commented
Whenever I see the word "microdelta" I uncontrollably think about this SNL skit https://www.youtube.com/watch?v=vEA4gzG-ooo

2021-03-04 06:33 UTC, tanishqaggarwal reviewed
(serious) I'd recommend making sure the propulsion system interrupt loop doesn't conflict with this one. Try running PropStateMachineCase on EDU.

2021-03-05 00:52 UTC, kylekrol commented
Something weird happen with the piksi control task files during merging it seemed like. Why does it think their are changes on every line? Did we go tabs to spaces or the other way around? Did we adjust indenting maybe? The diff shouldn't be that large...

2021-03-05 05:05 UTC, tanishqaggarwal commented
Might be a line endings thing.

2021-03-08 21:03 UTC, merged