Remove Last Fix Time
pathfinder-for-autonomous-navigation/FlightSoftware pull request #644
Opened 2021-02-26 00:25 UTC by shihaocao

# Remove Last Fix Time

last_fix_time as a field within PiksiControlTask, is not necessary anymore as the PiksiFaultHandler is based on control cycles anyways. Further, this will declutter the next PR.

### Summary of changes
-  Remove all mentions of last_fix_time, based off of actual real system time

2021-02-26 22:56 UTC, knk38 commented on ptest/cases/reboot_utility.py
> +        self.cycle
self.cycle()

2021-02-26 22:57 UTC, knk38 requested changes
change cycle to cycle()

2021-02-26 22:57 UTC, knk38 approved these changes

2021-02-27 17:06 UTC, kylekrol approved these changes

2021-02-27 17:30 UTC, merged