RadioSession dictionary
pathfinder-for-autonomous-navigation/FlightSoftware pull request #649
Opened 2021-02-27 20:31 UTC by afoarce

# RadioSession dictionary for uplink fields

Fixes #629 

### Summary of changes
- Added dictionary to RadioSession to automatically update fields written from ptest and command prompt cases and  before sending uplink when the timer runs out
- Changed file names of uplinks created from HTTP endpoints to avoid ptest overriding manual inputs
- Added merging feature between fields written in http_uplink.json and the RadioSession dictionary before fields are written to uplink.json, giving priority to the endpoint commands when conflicts exist

### Testing
Tested in ptest by having the tlm server running with elasticsearch. While running a testcase using radios, used combinations of sending ws commands through ptest only, ptest and http endpoints, and http endpoint only to verify emails are sent as expected. Tested using adcs.state, potential issues exist when sending other types of fields such as booleans which will need to be further tested but is not directly related to the dictionary update.

2021-03-03 04:49 UTC, shihaocao commented on ptest/configs/ci.json
> +            "connect": true,
What does this do?

2021-03-03 04:55 UTC, shihaocao commented on ptest/radio_session.py
> +        print(self.statefield_dict)
should this comment go?

2021-03-03 04:56 UTC, shihaocao commented on ptest/radio_session.py
> +        if not os.path.exists("uplink.json"):
Should we return false if the file already exists?

2021-03-03 04:57 UTC, shihaocao commented on ptest/radio_session.py
> +        if tlm_service_active and response.text.lower()=="true" and not os.path.exists("uplink.json") and not os.path.exists("http_uplink.json"):
this change looks good, but it looks like we don't use this function anymore? Will it ever be used in the future?

2021-03-03 05:09 UTC, shihaocao commented on ptest/radio_session.py
> +        success = self.uplink_console.create_uplink(fields, vals, "uplink.sbd", "uplink.http") and os.path.exists("uplink.sbd")
what is uplink.http, and what is in it?

2021-03-03 05:10 UTC, shihaocao commented on ptest/radio_session.py
> +        success = self.uplink_console.create_uplink(fields, vals, "uplink.sbd", "uplink.http") and os.path.exists("uplink.sbd")
Seems like we also refer to as the `json_filename` as an argument?

2021-03-03 05:10 UTC, shihaocao requested changes
Almost looks good, just wondering about a print statement and a few questions?

2021-03-06 17:35 UTC, fatimayousuf submitted a review, later dismissed

2021-03-06 17:35 UTC, fatimayousuf commented on ptest/configs/ci.json
> +            "connect": true,
It opens a radio session connected to the radio with that imei number. If connect is set to false, it won't open a radio session even if you put all that info in the config file

2021-03-06 17:35 UTC, fatimayousuf commented on ptest/radio_session.py
> +        success = self.uplink_console.create_uplink(fields, vals, "uplink.sbd", "uplink.http") and os.path.exists("uplink.sbd")
@afoarce I think maybe you meant http_uplink.json here?

2021-03-06 17:35 UTC, fatimayousuf commented on ptest/http_cmd.py
> +                    queued_uplink = json.load(telem_file)
The queued uplink connected to the uplink timer is `uplink.json`, and the requested uplink sent over http is 'http_uplink.json', right? So shouldn't `queued_uplink` hold the json object from uplink.json? Otherwise, in in line 114, when you update `queued_uplink`, you're just updating the requested http uplink, which loses the telemetry queued to be sent when the timer ran out

2021-03-07 00:42 UTC, afoarce commented on ptest/http_cmd.py
> +                    queued_uplink = json.load(telem_file)
Currently, uplink.json is empty and just used as a flag for the existence of an uplink to send on the timer, since RadioSession holds all the data in a dictionary and adds the http_uplink data right before making and sending the uplink when the timer runs out. I think then we only need to update http_uplink since it is the only json file holding data?

2021-03-07 00:45 UTC, afoarce commented on ptest/radio_session.py
> +        if not os.path.exists("uplink.json"):
I don't believe so - the point of the dictionary is that even if states have been written before we can continue doing so while the uplink timer is running. If an uplink doesn't exist yet, this statement makes the file and starts the timer.

2021-03-07 00:51 UTC, afoarce commented on ptest/radio_session.py
> +        if tlm_service_active and response.text.lower()=="true" and not os.path.exists("uplink.json") and not os.path.exists("http_uplink.json"):
That's a good point - the purpose for it that I saw was to make sure we don't overwrite uplinks when we could only write states once, but it says it can be used by ptest to determine whether to send uplinks autonomously. Does it actually tell us if Iridium received the last uplink, and should we add it back, or is it only checking that the service is active and we have an uplink to send?

2021-03-07 00:53 UTC, afoarce commented on ptest/radio_session.py
> +        success = self.uplink_console.create_uplink(fields, vals, "uplink.sbd", "uplink.http") and os.path.exists("uplink.sbd")
I think this one should be uplink.json, the file just created with the merged data

2021-03-07 03:28 UTC, shihaocao approved these changes

2021-03-07 04:03 UTC, merged