Microdelta check
pathfinder-for-autonomous-navigation/FlightSoftware pull request #666
Opened 2021-03-12 23:13 UTC by madeleinemc

Closes #663

Add a microdelta threshold; throws CRC error if microdelta is above threshold.
PiksiCheckoutCase performs normally when threshold set to 100ms. Throws CRC errors over half the time when threshold set to 50ms (as expected).

2021-03-12 23:15 UTC, kylekrol commented
@madeleinemc want to merge in or rebase off master so those previous Piksi commits aren't in here?

2021-03-12 23:18 UTC, madeleinemc commented
I did that afterward as part of the above commit :/

2021-03-12 23:27 UTC, kylekrol commented on src/fsw/FCCode/PiksiControlTask.cpp
> +    if (microdelta < 0 || microdelta > md_threshold) read_out = 3;
Also we should be careful here with comparing `signed` versus `unsigned` integers -- it can get weird depending on the situation. Iirc `microdelta` is signed so we only need to check that it's less than a threshold. It'd also probably be best PAN practice to make the threshold a tracked constant within flight software, something like:

    TRACKED_CONSTANT_SC(unsigned int, PIKSI_MD_THRESHOLD, 100000);
    ...

2021-03-12 23:28 UTC, kylekrol commented on src/fsw/FCCode/PiksiControlTask.cpp
> +    if (microdelta < 0 || microdelta > md_threshold) read_out = 3;
Lastly, referring to the Piksi mode enum directly rather than hard coding a three is probs a could idea in case the piksi modes get shifted around -- it'll be more robust to code changes going forward.

2021-03-13 03:51 UTC, shihaocao commented on src/fsw/FCCode/PiksiControlTask.cpp
> +    if (microdelta < 0 || microdelta > md_threshold) read_out = 3;
I think kyle means that `microdelta` is unsigned (not signed), and thus we only need to check it's below a certain threshold. I agree that the tracked constant is useful.

2021-03-13 03:52 UTC, shihaocao requested changes
PR looks good to me at a high level :) We should remove the psim changes tho, and we should also implement Kyle's suggestions

2021-03-13 08:14 UTC, madeleinemc commented on src/fsw/FCCode/PiksiControlTask.cpp
> +    if (microdelta < 0 || microdelta > md_threshold) read_out = 3;
The read_out result is a little different from the actual index of the respective state in piksi_mode_enum. read_out has 6 possible values while piksi has 14 modes

2021-03-13 08:14 UTC, madeleinemc commented on src/fsw/FCCode/PiksiControlTask.cpp
> +    if (microdelta < 0 || microdelta > md_threshold) read_out = 3;
Will do

2021-03-13 10:33 UTC, shihaocao commented on src/fsw/FCCode/PiksiControlTask.cpp
> +    if (microdelta < 0 || microdelta > md_threshold) read_out = 3;
Oh that's right, i forgot the read out values are hardcoded, that sucks

2021-03-13 10:33 UTC, shihaocao commented on src/fsw/FCCode/PiksiControlTask.cpp
> +    if (microdelta < 0 || microdelta > md_threshold) read_out = 3;
my bad lul

2021-03-13 15:08 UTC, kylekrol commented on src/fsw/FCCode/PiksiControlTask.cpp
> +    if (microdelta < 0 || microdelta > md_threshold) read_out = 3;
Cool and yeah sorry I meant unsigned -- update the comment.

2021-03-13 15:09 UTC, kylekrol commented on src/fsw/FCCode/PiksiControlTask.cpp
> +    if (microdelta < 0 || microdelta > md_threshold) read_out = 3;
Ooohhh aight then yeah never mind -- hard coded it is!

2021-03-13 15:10 UTC, kylekrol commented
> PR looks good to me at a high level :) We should remove the psim changes tho, and we should also implement Kyle's suggestions

There are also still the phanton commits that ended up getting squashed in the previous Piksi related PR -- perhaps updating the branch below will fix it?

2021-03-15 08:03 UTC, shihaocao approved these changes
Good to go!

2021-03-15 08:24 UTC, merged