Quake Fault Handler ptest case
pathfinder-for-autonomous-navigation/FlightSoftware pull request #667
Opened 2021-03-13 02:56 UTC by 18kudlugim

- replaces quakefaulthandler.py PTest case
- I am unsure whether the power cycling behavior translates to HITL within the same cycle limit/timeframe as in HOOTL. It might take some more time

2021-03-13 03:45 UTC, shihaocao commented on ptest/cases/quake_power_cycling.py
> +        return float("inf")
Looks like we got simulation active in this test case, I don't think its necessary right?

2021-03-13 03:46 UTC, shihaocao commented on ptest/cases/utils.py
> +        "disabled"
wow, thanks for catching this, would probably screw us over later in debugging

2021-03-13 03:55 UTC, shihaocao commented on ptest/cases/quake_power_cycling.py
> +        self.ws("radio.state", 0)
What is 0? Can we change this to a radio state enum ref?

2021-03-13 03:57 UTC, shihaocao commented on ptest/cases/quake_power_cycling.py
> +        while True:
can we change this to a for loop just so its a bit more clear?

2021-03-13 04:02 UTC, shihaocao commented on ptest/cases/quake_power_cycling.py
> +        self.read_state("gomspace.power_cycle_output3_cmd")
did you want these to be `print_rs` calls?

2021-03-13 04:03 UTC, shihaocao commented on ptest/cases/quake_power_cycling.py
> +        self.read_state("gomspace.power_cycle_output3_cmd")
otherwise these readstates wont do anything since ptest doesn't have a caching system

2021-03-13 04:10 UTC, shihaocao commented on ptest/cases/quake_power_cycling.py
> +        output = self.rs("gomspace.output.output3")
seems like this is unused

2021-03-13 04:13 UTC, shihaocao commented on ptest/cases/quake_power_cycling.py
> +        return float("inf")
probably remove this entirely

2021-03-13 05:08 UTC, shihaocao requested changes
Thanks for getting this out so fast! I think there are a few small things to fix (outlined in comments)

I guess the one feature I think this is still missing is checking that the QauekFaultHanlder suggests the right `fault_response_t`, I think we should be stepping flight software forward, and always check that the right fault response was raised by seeing if MissionManager switches to the correct states

2021-03-19 03:33 UTC, 18kudlugim commented on ptest/cases/quake_power_cycling.py
> +        output = self.rs("gomspace.output.output3")
yea I had a comment underneath about a section that prints the gomspace output channel (for power cycling testing in HITL), but was unsure how it'll translate. As is, the checkout case essentially power cycles immediately in HOOTL and checks this behavior, but power cycling may lag a bit in HOOTL and I wasn't sure whether to add this because of that.

2021-03-19 03:37 UTC, 18kudlugim commented on ptest/cases/quake_power_cycling.py
> +        self.read_state("gomspace.power_cycle_output3_cmd")
I think it's a bit noisy to print every cycle. I mainly had the read_states so the values could be accessed for plotting

2021-03-19 07:04 UTC, tanishqaggarwal commented on ptest/cases/utils.py
> +        "disabled"
Agreed. Also, i've confirmed it's in the same order as the corresponding fsw enum file

2021-03-23 20:38 UTC, shihaocao requested changes
Looks good on the MissionManager checks, I just had one more requested change sorry

It seems like given that we modified the QuakeFaultHandler to also mutate quake state, could we check that the quake state gets mutatued properly? (ex disabled when disabled, config when config)

2021-03-23 20:39 UTC, shihaocao commented on ptest/cases/quake_power_cycling.py
> +                    raise TestCaseFailure(f"QuakeFaultHandler did not force satellite into standby during during QuakeFaultHandler's `forced standby` state. State was: {self.mission_state}. Current c
```suggestion
                raise TestCaseFailure(f"QuakeFaultHandler did not force satellite into standby during during QuakeFaultHandler's `forced standby` state. State was: {self.mission_state}. Current control cycle: {self.rs('pan.cycle_no')}")
```

2021-03-23 20:40 UTC, shihaocao commented on ptest/cases/quake_power_cycling.py
> +                    raise TestCaseFailure(f"QuakeFaultHandler did not force satellite into standby after 24 hours of no comms. State was: {self.mission_state}. Current control cycle: {self.rs('pan.cy
```suggestion
            raise TestCaseFailure(f"QuakeFaultHandler did not force satellite into standby after 24 hours of no comms. State was: {self.mission_state}. Current control cycle: {self.rs('pan.cycle_no')}")
```

2021-03-23 20:58 UTC, shihaocao approved these changes
nice

2021-03-23 20:59 UTC, merged