Kill switch
pathfinder-for-autonomous-navigation/FlightSoftware pull request #705
Opened 2021-04-06 01:34 UTC by angelaloh09

# Kill Switch Upgrade to Mission Manager 

Fixes:  #683

### Summary of changes
- Created kill_switch state field. Write 127 to kill switch field so spacecraft no longer tries to make contact with ground. 
- Placed the check for kill switch and while-true loop under dispatch_startup(), so every time the spacecraft reboots, it will check the kill switch flag in startup mode.  

### Testing
- Ran a HOOTL test with PsimDebug, set kill switch flag to 127 with `ws kill_switch 127`, and sent ptest to not respond/error out because of the while true loop when running PsimDebug again. 
- Ran a HITL test with the EduSat with EmptyCase. First, uncommented line 129 of MainControlLoop `eeprom_controller.execute_on_time()` to execute the eeprom_controller, which was original commented out to save write cycles. Then, read the initial kill_switch flag, which returned 0. Wrote the kill_switch flag to 127. Waited for 200 cycles. (Current cycle update for kill_switch is 100). Reran EmptyCase, the ptest terminal errored out because of the while true loop (screenshot attached, titled "Image 1"). To double-check the EduSat can function properly with the kill_switch code, we changed the checked flag value to 126 `if (kill_switch_f.get() == 126)`, and the ptest returned back to normal without any errors. 

<img width="1262" alt="Screen Shot 2021-04-03 at 2 48 59 PM" src="https://user-images.githubusercontent.com/44074422/113645953-d54e5800-9655-11eb-8a86-ab7f1ea1f0ef.png">

_Image 1: Ptest errored out when re-running EmptyCase (after setting kill switch flag to 127._ 

<img width="975" alt="Screen Shot 2021-04-03 at 2 50 35 PM" src="https://user-images.githubusercontent.com/44074422/113646116-28280f80-9656-11eb-845e-8bb563f8d08e.png">
_Image 2: Set flag check value to 126, reran EmptyCase, Ptest worked without erroring out_

### Documentation Evidence
- Inline documentation is sufficient. 
- Before the kill_switch flag check, wrote "Step 0. If kill switch flag is set, shuts down radio connection." Inside the while true loop, commented "This will cause gomspace to reboot the spacecraft and we will get stuck in this loop forever." The inline documentation is sufficient because it clearly states what the kill_switch flag is for do, how to set it to either shut down or not shut down the radio connection, and the effects of enabling the kill_switch.

2021-04-06 08:13 UTC, shihaocao commented on ptest/usb_session.py
> +        # self.http_thread.join()
let's remove all the changes on this file for now, and we can address this issue in a more permanent fashion this week

2021-04-06 08:14 UTC, shihaocao commented on src/fsw/FCCode/EEPROMControllerTeensy.cpp
> +  while (EEPROM.read(addresses[position]) != _registry.eeprom_saved_fields[position]->get_eeprom_repr()){
we should only attempt it once, would an `if` statement work instead?

We don't want to get stuck in a while loop if EEPROM is laggy or locks up

2021-04-06 08:16 UTC, shihaocao commented on src/fsw/FCCode/MissionManager.cpp
> +        else if (fault_response == fault_response_t::standby && state != mission_state_t::safehold && state != mission_state_t::initialization_hold && state != mission_state_t::detumble && state != m
let's undo this line change? I think the old formatting was good

2021-04-06 08:18 UTC, shihaocao commented on src/fsw/FCCode/MissionManager.hpp
> +     * from spacecraft with ground
Perhaps this comment should be revised to talk about the switch as a command, rather than the specific state?

2021-04-06 08:19 UTC, shihaocao requested changes
Solid code changes, just some quick formatting items, and one question about the while loop

2021-04-06 08:20 UTC, shihaocao commented on src/fsw/FCCode/MissionManager.cpp
> +    if (kill_switch_f.get() == 127)
Let's put this as a tracked constant. Perhaps look at how many other constants are wrapped in TRACKED_CONSTANT xxxxx etc

2021-04-06 08:24 UTC, shihaocao commented on src/fsw/FCCode/MissionManager.cpp
> +      kill_switch_f("pan.kill_switch", Serializer<unsigned char>(3))
This code seems incomplete, there's no EEPROM save duration constructor call?

Additionally, what is a good EEPROM save duration? Perhaps once every 100 cycles?

2021-04-06 14:51 UTC, kylekrol commented on src/fsw/FCCode/EEPROMControllerTeensy.cpp
> +  while (EEPROM.read(addresses[position]) != _registry.eeprom_saved_fields[position]->get_eeprom_repr()){
Don't we not want to include EEPROM changes in this PR?

2021-04-07 07:38 UTC, shihaocao commented on src/fsw/FCCode/MissionManager.hpp
> +    TRACKED_CONSTANT_SC(unsigned char, kill_switch_value, 0);
we should have this as 127

2021-04-07 07:39 UTC, shihaocao commented on src/fsw/FCCode/MissionManager.hpp
> +    TRACKED_CONSTANT_SC(unsigned char, kill_switch_value, 0);
the magic byte value

2021-04-07 07:39 UTC, shihaocao commented on src/fsw/FCCode/MissionManager.cpp
> +    if (kill_switch_f.get() == 127)
and then use the tracked constant here

2021-04-07 07:40 UTC, shihaocao requested changes
Looks good! Lets make sure to use the tracked constant, and unstage the changes to psim

2021-04-10 14:44 UTC, kylekrol commented on src/fsw/FCCode/MissionManager.cpp
> +      kill_switch_f("pan.kill_switch", Serializer<unsigned char>(3), 100)
Two things here:

 * Why did we add the `sat_designation_f` field to EEPROM? I thought @shihaocao had gotten rid of this?
 * The serializer for the kill switch right now can only take on values from `0-3` which means we'd never be able to uplink the required kill switch value.

2021-04-10 14:56 UTC, kylekrol commented on ptest/usb_session.py
>  class USBSession(object):
Are any of the changes here required for the PR? If not we should probably just avoid changes and keep the diff for this PR as simple as possible.

2021-04-10 18:18 UTC, kylekrol approved these changes
lgtm!

2021-04-10 18:19 UTC, merged