Piksifaulthandler
pathfinder-for-autonomous-navigation/FlightSoftware pull request #708
Opened 2021-04-08 23:20 UTC by 18kudlugim

Piksi Fault Handler checks three conditions before moving mission state to standby.

After shifting the last_rtkfix_ccno field from PiksiControlTask.cpp to PiksiFaultHandler.cpp, it's failing to pass some unit tests [WIP]. Regarding the PTest, checking the third condition after having checked the second condition results in the mission state being prematurely set to standby. However, since the unit tests aren't passing, this could have something to do with the PiksiFaultHandler implementation.

2021-04-10 05:33 UTC, shihaocao commented on test/test_fsw_mission_manager/test_fixture.cpp
> +    // last_rtkfix_ccno_fp = registry.find_internal_field_t<unsigned int>("piksi.last_rtkfix_ccno");
i think mission manager still needs this field, except now its coming from the fault handler

2021-04-10 05:33 UTC, shihaocao commented on test/test_fsw_mission_manager/test_fixture.cpp
> +    // last_rtkfix_ccno_fp = registry.find_internal_field_t<unsigned int>("piksi.last_rtkfix_ccno");
and now its readable

2021-04-11 14:43 UTC, kylekrol commented on ptest/configs/hitl_singlesat.json
> +>>>>>>> Stashed changes
We committed a merge conflict here.

2021-04-11 14:44 UTC, kylekrol commented on src/fsw/FCCode/Estimators/RelativeOrbitEstimator.cpp
>  static inline auto get_gps_zero()
Can we undo the changes here that are purely formatting? It's just going to clutter the git blame and it'll be more difficult to track down whose actually responsible for what code in the future.

2021-04-11 14:48 UTC, kylekrol commented on ptest/configs/hitl_singlesat.json
> +            "port": "/dev/cu.usbmodem73392101",
Let's also not commit this change here as it's different for everyone.

2021-04-11 14:49 UTC, kylekrol commented on src/fsw/FCCode/PiksiControlTask.cpp
> -        add_readable_field(microdelta_f);
Same with this file, we shouldn't do a bunch of formatting stuff without make a substantive change in the file.

2021-04-11 14:49 UTC, kylekrol commented on src/fsw/FCCode/PiksiControlTask.hpp
> +    // InternalStateField<unsigned int> last_rtkfix_ccno_f;
If we don't need it we can just delete it?

2021-04-13 20:53 UTC, 18kudlugim commented on ptest/configs/hitl_singlesat.json
> +            "port": "/dev/cu.usbmodem73392101",
whoops didn't realize I commited this

2021-04-14 05:29 UTC, shihaocao commented on ptest/configs/hitl_singlesat.json
> +            "port": "/dev/cu.usbmodem73392101",
bump to remove this

2021-04-14 05:29 UTC, shihaocao commented on src/fsw/FCCode/PiksiControlTask.cpp
> -        add_readable_field(microdelta_f);
bump to checkout this file from master

2021-04-14 05:31 UTC, shihaocao commented on src/fsw/FCCode/PiksiFaultHandler.hpp
> +#include "TimedControlTask.hpp"
bump to undo formatting overall on this file

2021-04-14 05:31 UTC, shihaocao commented on src/fsw/FCCode/PiksiFaultHandler.hpp
> +#include <common/constant_tracker.hpp>
we should keep these only if they are critical for build

2021-04-14 05:38 UTC, shihaocao commented on src/fsw/FCCode/PiksiFaultHandler.cpp
> +        return fault_response_t::safehold;
@18kudlugim @madeleinemc This fault response will break pending both PR's being merged in. As soon as we flip into detumble, the piksi would still be dead.

Maybe this is the time we finally remove the piksi dead state, and replace it with a fault that's signaled whenever the piksi_state is in an error state. And then only incrementing signaling whenever we're not in standby

2021-04-14 05:39 UTC, shihaocao commented on src/fsw/FCCode/PiksiFaultHandler.cpp
> +    }
this is good

2021-04-14 05:39 UTC, shihaocao commented on src/fsw/FCCode/PiksiFaultHandler.cpp
> +PiksiFaultHandler::PiksiFaultHandler(StateFieldRegistry &r)
bump to undo formatting changes

2021-04-14 05:41 UTC, shihaocao requested changes
Biggest thing is the fact that we're going to have an upcoming problem with the PiksiFaultHandler potentially interacting badly with the PiksiDontStart code package change. @madeleinemc @18kudlugim could you both update each other on this?

2021-04-15 03:20 UTC, 18kudlugim commented on src/fsw/FCCode/PiksiControlTask.cpp
> -        add_readable_field(microdelta_f);
Ahh it autoformatted when I saved :')

2021-04-15 03:22 UTC, 18kudlugim commented on src/fsw/FCCode/PiksiControlTask.cpp
> -        add_readable_field(microdelta_f);
I am removing all instances of last_rtkfix_ccno_f in the file. Does that count as a substantive change?

2021-04-15 03:26 UTC, 18kudlugim commented on src/fsw/FCCode/PiksiFaultHandler.cpp
> +PiksiFaultHandler::PiksiFaultHandler(StateFieldRegistry &r)
Are these just formatting changes? I've added the last_rtkfix_ccno_f state field in the constructor and all, that's why the lines have shifted down

2021-04-16 18:56 UTC, shihaocao commented on src/fsw/FCCode/PiksiFaultHandler.cpp
> +PiksiFaultHandler::PiksiFaultHandler(StateFieldRegistry &r)
Yeah sorry like, indeed your line is import and should remain, but we shouldn't reformat all the other lines. in this file that are not related to your change.

2021-04-17 18:25 UTC, shihaocao approved these changes
Sick

2021-04-17 18:43 UTC, merged