PTest Restructuring
pathfinder-for-autonomous-navigation/FlightSoftware pull request #713
Opened 2021-04-13 00:15 UTC by kylekrol

### Summary of changes
- The boot utility is gone!!!
- Restructured how a simulation plugs in to a simulation. Now, the simulation is pulled in as a mixin class and cycling actually now steps the simulation forward as well.
- Moved to constructor flags instead of properties to reduce clutter and actually leverage inheritance.

### Testing

We'll be happy if all the tests still work!

2021-04-15 04:19 UTC, tanishqaggarwal commented on ptest/cases/boot_to.py
> +from .base import SingleSatCase, PSimCase
The fact that psim works cleanly enough to allow this kind of drop-in testcase writing is just *chef's kiss*

2021-04-15 04:19 UTC, tanishqaggarwal commented on ptest/cases/boot_to.py
> +class BootToStartupCase(SingleSatCase, PSimCase):
Technically this doesn't need to be a psim case right? Is there value to creating a separate non-psim case?

2021-04-15 04:19 UTC, tanishqaggarwal commented on ptest/cases/piksi_checkout_case.py
> +        self.mission_state = "manual"
Why?

2021-04-15 04:19 UTC, tanishqaggarwal commented on ptest/cases/prop_fault_handler.py
> +        self.psim_config_overrides["truth.leader.attitude.w"] = lin.Vector3([0.01,0.0711,-0.01])
Why is this override needed?

2021-04-15 04:19 UTC, tanishqaggarwal commented on ptest/cases/prop_state_machine_case.py
> +            "pan.state", Enums.mission_states["manual"])
```suggestion
        self.mission_state = 'manual'
```

2021-04-15 04:19 UTC, tanishqaggarwal commented on ptest/cases/psim_debug.py
> +        self.psim_config_overrides["truth.leader.attitude.w"] = lin.Vector3([0.01,0.0738,-0.01])
Why is this needed?

2021-04-15 04:19 UTC, tanishqaggarwal commented on ptest/cases/quake_power_cycling.py
> +#        self.initial_state = "standby"
```suggestion
```

2021-04-15 04:19 UTC, tanishqaggarwal commented on ptest/cases/safehold_reboot.py
> +        self.psim_config_overrides["truth.leader.attitude.w"] = lin.Vector3([0.01,0.0711,-0.01])
Why this override

2021-04-15 04:19 UTC, tanishqaggarwal commented on ptest/cases/safehold_reboot.py
> +import lin
Can remove this import if the override is not needed

2021-04-15 04:19 UTC, tanishqaggarwal commented on ptest/cases/simple_fault_handlers.py
> +        self.psim_config_overrides["truth.leader.attitude.w"] = lin.Vector3([0.01,0.0711,-0.01])
Override required?

2021-04-15 04:19 UTC, tanishqaggarwal commented on ptest/cases/simple_fault_handlers.py
> +        self.psim_config_overrides["truth.leader.attitude.w"] = lin.Vector3([0.01,0.0711,-0.01])
Override required?

2021-04-15 04:19 UTC, tanishqaggarwal commented on ptest/cases/reset_for_flight.py
> +        self.set_confirm("pan.deployed", False)
These flags are redundant...are we still using both of them in FSW? The condition deployed is equivalent to deployment.elapsed >= 30 mins

2021-04-15 04:19 UTC, tanishqaggarwal commented on ptest/cases/reset_for_flight.py
> +        #make sure spacecraft is shut down right after this test case so mission doesnt start executing
Is shutting down the spacecraft up to the testcase operator? How might we be able to enforce this?

2021-04-15 04:19 UTC, tanishqaggarwal commented on ptest/cases/reset_for_flight.py
> +        self.cycle()
Why call self.cycle() when cycle.auto may be true?

2021-04-15 12:27 UTC, kylekrol commented on ptest/cases/boot_to.py
> +class BootToStartupCase(SingleSatCase, PSimCase):
No but what we're trying to go for here is booting with the simulation and sensor data more often. These essentially test for regressions in full mission cases.

Also, I'm not sure about the value of having the satellite in something like standby without sensor data -- we replaced all testcases that required it with a `psim` testcase.

2021-04-15 12:28 UTC, kylekrol commented on ptest/cases/piksi_checkout_case.py
> +        self.mission_state = "manual"
Lot's of people tried to fast boot to manual and this is the equivalent. It worries me tho that github says this is in the `setup_post_bootsetup` function when it should just be `post_boot` @shihaocao?

2021-04-15 12:29 UTC, kylekrol commented on ptest/cases/prop_fault_handler.py
> +        self.psim_config_overrides["truth.leader.attitude.w"] = lin.Vector3([0.01,0.0711,-0.01])
#720.

2021-04-15 12:29 UTC, kylekrol commented on ptest/cases/simple_fault_handlers.py
> +        self.psim_config_overrides["truth.leader.attitude.w"] = lin.Vector3([0.01,0.0711,-0.01])
#720.

2021-04-15 12:29 UTC, kylekrol commented on ptest/cases/simple_fault_handlers.py
> +        self.psim_config_overrides["truth.leader.attitude.w"] = lin.Vector3([0.01,0.0711,-0.01])
#720.

2021-04-15 12:30 UTC, kylekrol commented on ptest/cases/reset_for_flight.py
> +        #make sure spacecraft is shut down right after this test case so mission doesnt start executing
Yeah we could change this so that it manually cycles a certain number of times. Separate ticket though I'd say.

2021-04-15 12:30 UTC, kylekrol commented on ptest/cases/reset_for_flight.py
> +        #make sure spacecraft is shut down right after this test case so mission doesnt start executing
Oh wait but we can't because autocycle would be true...

2021-04-15 13:52 UTC, kylekrol commented on ptest/cases/reset_for_flight.py
> +        #make sure spacecraft is shut down right after this test case so mission doesnt start executing
Seems like we may need to open a ticket for this case in general @shihaocao?

2021-04-15 14:07 UTC, tanishqaggarwal commented on ptest/cases/reset_for_flight.py
> +        #make sure spacecraft is shut down right after this test case so mission doesnt start executing
I feel like this is OK just as long as the operator actually shuts down the spacecraft. Spending a few cycles in the startup deployment phase is no biggie really

2021-04-15 15:19 UTC, kylekrol commented on ptest/cases/reset_for_flight.py
> +        #make sure spacecraft is shut down right after this test case so mission doesnt start executing
Ah true true as long as we run it in realtime.

2021-04-15 15:21 UTC, kylekrol commented on ptest/cases/reset_for_flight.py
> +        self.set_confirm("pan.deployed", False)
Also a good point haha Can take a look at this a little later.

2021-04-16 02:07 UTC, madeleinemc requested changes
I think it looks good! I looked over the description and new base files, as well as focusing on PiksiCheckoutCase and GomspaceCheckoutCase

2021-04-16 02:07 UTC, madeleinemc commented on ptest/cases/gomspace_checkout_case.py
>          self.failed = False
set gomspace.piksi_off to false

2021-04-16 16:55 UTC, kylekrol commented on ptest/cases/gomspace_checkout_case.py
>          self.failed = False
Is this something that should go in this PR or should that be included somewhere else?

2021-04-16 17:54 UTC, madeleinemc commented on ptest/cases/gomspace_checkout_case.py
>          self.failed = False
Ohh yeah but will it be overwritten by this change to gomspace_checkout_case?

2021-04-16 19:00 UTC, shihaocao commented on ptest/cases/gomspace_checkout_case.py
>          self.failed = False
Im suprised that CI didn't catch this spooky interaction on the last PR

2021-04-16 19:25 UTC, kylekrol commented on ptest/cases/gomspace_checkout_case.py
>          self.failed = False
Seems like it's just because we were hard setting the sat into manual.

2021-04-16 19:31 UTC, shihaocao commented on ptest/cases/reset_for_flight.py
> +        self.cycle()
If it is true, then cycling is fine here anyway

2021-04-16 19:50 UTC, madeleinemc approved these changes

2021-04-16 20:45 UTC, 18kudlugim approved these changes
Looks pretty solid, everything in the PR overview matches what's in the base folder, etc., and the PTest cases now all run locally

2021-04-16 21:02 UTC, Duncan-McD approved these changes
Looks good to me

2021-04-16 21:05 UTC, merged