Close approach gnc
pathfinder-for-autonomous-navigation/FlightSoftware pull request #717
Opened 2021-04-14 04:16 UTC by govindchari

# Close Approach GNC

### Summary of changes
- Increased number of firing in near-field
- Decreased gains in near-field

2021-04-15 04:28 UTC, tanishqaggarwal reviewed
*read in Bill Clinton's reedy Arizonian voice* y'all call this GNC? back in mah day we wrote e'erything in matlab or ain't worth shit. can't deal with all of this C++ mumbo jumbo y'all call guidance these days. what the HECK is going on

2021-04-15 04:28 UTC, tanishqaggarwal commented on src/fsw/FCCode/OrbitController.cpp
> +            next_node(firing_nodes_near) : next_node(firing_nodes_far);
This one-liner is difficult to parse, I would suggest breaking it out into several lines

2021-04-15 04:28 UTC, tanishqaggarwal commented on src/fsw/FCCode/OrbitController.cpp
> +    }
```suggestion
    data.p = gnc::constant::K_p;
    data.d = gnc::constant::K_d;
    data.energy_gain = gnc::constant::K_e;   // Energy gain                   (J)
    data.h_gain = gnc::constant::K_h;        // Angular momentum gain         (kg m^2/sec)
    
    if (rel_orbit_state==static_cast<unsigned char>(rel_orbit_state_t::estimating)) {
        data.p /= gain_factor;  
        data.d /= gain_factor;
        data.energy_gain /= gain_factor;
        data.h_gain /= gain_factor;
    }
```

2021-04-15 12:47 UTC, kylekrol commented on src/fsw/FCCode/OrbitController.cpp
> +auto gain_factor = (double)(firing_nodes_near.size() / firing_nodes_far.size());
We actually need to cast first otherwise it's still going to do integer math and only then cast to a double. No reason not to make this `static constexpr` either.
```suggestion
static constexpr auto gain_factor = static_cast<double>(firing_nodes_near.size()) / firing_nodes_far.size();
```

2021-04-15 12:49 UTC, kylekrol commented on src/fsw/FCCode/OrbitController.cpp
> +    J_ecef_f("orbit.control.J_ecef", Serializer<lin::Vector3d>(0,10,100))
We should be careful with these serializer values here! We don't need `100` bits resolution on the vector's magnitude. For reference the arguments go:

    Serializer<lin::Vector3d>(min_magnitude, max_magnitude, bits_for_magnitude)

2021-04-15 12:50 UTC, kylekrol commented on src/fsw/FCCode/OrbitController.cpp
> +    J_ecef_f.set(0.0);
Perhaps you mean this? That being said, `lin` types are guaranteed to default construct full of zeros -- part of them being `constexpr` types.
```suggestion
    J_ecef_f.set(lin::zeros<lin::Vector3d>());
```

2021-04-15 12:52 UTC, kylekrol commented on src/fsw/FCCode/OrbitController.cpp
> +            next_node(firing_nodes_near) : next_node(firing_nodes_far);
Lolll I was actually the one who suggested doing this instead of having it turn into a mutliple return statement function and what not. Making it an `if` `else` would just be the same number of lines pretty much?

2021-04-15 12:53 UTC, kylekrol commented on src/fsw/FCCode/OrbitController.cpp
> +    }
This definitely seems to be the way to go.

2021-04-15 12:54 UTC, kylekrol reviewed
Looks like we're definitely heading in the right direction here -- once we get CI figured out should be good to go pretty quickly.

2021-04-15 12:58 UTC, kylekrol commented on src/fsw/FCCode/OrbitController.cpp
> +            }
Keeping `min_time` outside of the lambda but then still returning it is, at the very least, weird and we should move it into the local scope something like this:
```suggestion
    auto next_node = [&](auto const &arr) -> double {
        auto min_time = std::numeric_limits<double>::max();
        for (auto const node : arr) {
            auto const time_til_node = (node - theta) / ang_vel;
            if (time_til_node > 0 && time_til_node < min_time) {
                min_time = time_til_node;
            }
```
Also, we can use a range based for loop if we want! Just don't forget to remove line 127/151 if you go with this change.

2021-04-16 16:52 UTC, kylekrol commented on src/fsw/FCCode/OrbitController.cpp
> +    J_ecef_f("orbit.control.J_ecef", Serializer<lin::Vector3d>(0,0.1,10))
Is there really not a place we can pull this constant from? Having a random magic number floating around really isn't ideal...

2021-04-16 16:54 UTC, kylekrol reviewed
All the flight software changes look good to me assuming @fatimayousuf is good with them as well. Otherwise, I think you just need to update the orbit controller unit tests and maybe look into adding something to test the close approach behavior if that seems feasible.

2021-04-18 18:46 UTC, fatimayousuf approved these changes
Orbit controller changes look fine to me! I'd wait on Kyle's approval though since he's a lot more knowledgeable of GNC stuff than I am.

2021-04-18 19:09 UTC, kylekrol commented on src/fsw/FCCode/OrbitController.cpp
> +    }
I worry about the exponential filtering happening here. We want to be sure that the filtering is happening on every time step regardless of what the orbit controller is doing (perhaps it's disabled at a given time step because the attitude estimator is broken or something)?

I'd suggest moving the exponential filter logic to the very start of execute and have a single check like:

    if (relative orbit estimate is valid) {
        do the exponential filtering and/or initialization if things are NaNs
    } else {
        set things to NaNs because we don't want old filtered values hanging around
    }

2021-04-18 19:09 UTC, kylekrol commented on src/fsw/FCCode/OrbitController.cpp
> +    alpha_f.set(0.4);
We want to initialize the filtered values to `lin::nans<lin::Vector3d>()` here too otherwise the filter is gonna think it was already initialized.

2021-04-18 19:10 UTC, kylekrol commented on src/fsw/FCCode/OrbitController.cpp
> +
```suggestion
    alpha_f("orbit.control.alpha", Serializer<double>(0,1,10))
```

2021-04-18 19:11 UTC, kylekrol requested changes
I think we need to shift where the exponential filtering is happening to avoid bugs where the relative orbit estimate was valid and then all of a sudden became invalid again. Otherwise, it looks great.

2021-04-18 19:41 UTC, kylekrol commented on src/fsw/FCCode/OrbitController.cpp
> +    const lin::Vector3d &dr_smoothed, const lin::Vector3d &dv_smoothed) {
I think we should change the name of the input parameters just back to `dr` `dv` here as the function doesn't really care if it's handling smoothed data or not.
```suggestion
    const lin::Vector3d &dr, const lin::Vector3d &dv) {
```

2021-04-18 19:42 UTC, kylekrol commented on src/fsw/FCCode/OrbitController.cpp
> +    data.dv_ecef = dv_smoothed;
```suggestion
    data.dr_ecef = dr;
    data.dv_ecef = dv;
```

2021-04-18 19:42 UTC, kylekrol commented on src/fsw/FCCode/OrbitController.cpp
> +    alpha_f.set(0.4);
```suggestion
    J_ecef_f.set(lin::zeros<lin::Vector3d>());
    alpha_f.set(0.4);
    dr_smoothed = lin::nans<lin::Vector3d>();
    dv_smoothed = lin::nans<lin::Vector3d>();
```

2021-04-18 19:51 UTC, kylekrol approved these changes
Seems good to me assuming CI goes through!

2021-04-18 20:08 UTC, merged