Piksi Dead as a Fault
pathfinder-for-autonomous-navigation/FlightSoftware pull request #739
Opened 2021-04-19 09:36 UTC by shihaocao

# Piksi Dead as a Fault

Fixes #694, #98

### Summary of changes
- piksi_mode_t::dead was created in a time before faults, it is time it is upgraded so we can fine-grain control over it
- updated PiksiFaultHandler.cpp
- TODO update piksi_fault_handerl.py ptest

### Testing
-

### Constants
-

### Telemetry
Add piksi_fh.dead.base

2021-04-19 15:56 UTC, kylekrol requested changes

2021-04-19 15:56 UTC, kylekrol commented on src/fsw/FCCode/PiksiFaultHandler.cpp
> +    // begin rtk section
All of this logic can be placed into the `SimpleFaultHandler` thing. All you should need to do here is signal on the Piksi state.

2021-04-19 15:56 UTC, kylekrol commented on src/fsw/FCCode/PiksiFaultHandler.cpp
> +    // begin rtk section
Look at my PR for the attitude orbit estimator fault for reference.

2021-04-19 15:56 UTC, kylekrol commented on src/fsw/FCCode/PiksiFaultHandler.hpp
> +    TRACKED_CONSTANT_SC(unsigned int, piksi_dead_threshold, PAN::one_day_ccno/6);
This would become the fault persistence value.

2021-04-19 15:56 UTC, kylekrol commented on test/test_fsw_fault_handler/test_piksi_fault_handler.cpp
> +    TEST_ASSERT_TRUE(tf.pfh->piksi_dead_fault_f.is_faulted());
You also then wouldn't need to write a unit test haha Just a simple PTest case where we initialize everything and then write `sensors.leader.gps.disabled` to `True`.

2021-04-19 17:27 UTC, kylekrol commented
We're gonna keep things centralized in Piksi fault handler and not use simple fault handler.

2021-04-20 21:16 UTC, 18kudlugim commented on src/fsw/FCCode/PiksiFaultHandler.cpp
> +        return fault_response_t::standby;
I think we discussed earlier that the fault response here should move mission state to safehold?

2021-04-28 04:30 UTC, shihaocao commented on src/fsw/FCCode/PiksiFaultHandler.cpp
> +        return fault_response_t::standby;
I think we discussed this to be just standby is sufficient, the reasoning being that if we can be standby we should just stay in standby. GPSs not working shouldn't put the satellite in danger so long as the estimators are ok.

2021-04-30 09:07 UTC, shihaocao reviewed
I implicitly approve! I can't approve my own PR haha

2021-05-03 20:24 UTC, 18kudlugim approved these changes
Looks good!

2021-05-03 20:49 UTC, merged