Prop Validation
pathfinder-for-autonomous-navigation/FlightSoftware pull request #775
Opened 2021-05-12 03:04 UTC by govindchari

# Prop Fixes

Fixes #761 #750 

### Summary of changes
- Rebound statefields to avoid valve schedule duplication
- To fix #750 you must ws the Tank2 pressure above the threshold to transition from pressurizing into await firing
- Added a Tank2 pressure for nearfield (currently it is arbitrarily set at 15psi)
- Added a second set of regression constants to convert the desired impulse into thruster on times

TODO:
Choose good value for Nearfield Tank2 pressure
Compute the regression constants based on theory (ideally would perform empirical tests)

### Testing
In HOOTL a firing does occur as given by
<img width="1440" alt="Screen Shot 2021-05-11 at 11 00 08 PM" src="https://user-images.githubusercontent.com/6196536/117912057-cdb14d00-b2ac-11eb-9123-9e01cb8bb21a.png">
Also the threshold is working
<img width="506" alt="Screen Shot 2021-05-11 at 11 00 25 PM" src="https://user-images.githubusercontent.com/6196536/117912090-d86be200-b2ac-11eb-95fb-c731f67a1975.png">

### Constants
Two tracked constants are added: valve_time_lin_reg_intercept_near and valve_time_lin_reg_slope_near

2021-05-12 22:43 UTC, fatimayousuf requested changes
Looks great!

2021-05-12 22:43 UTC, fatimayousuf commented on src/fsw/FCCode/PropController.cpp
> +
I think you can just get rid of this now?

2021-05-12 22:43 UTC, fatimayousuf commented on src/fsw/FCCode/PropController.hpp
> +
delete this too

2021-05-12 22:43 UTC, fatimayousuf commented on src/fsw/FCCode/OrbitController.cpp
> +    }
Can you move this calculation to the execute() function like you did in Prop Controller, perhaps before when schedule_valves() is called? Then you don't need to pass the state to schedule_valves() or impulse_to_time().

2021-05-12 22:43 UTC, fatimayousuf commented on src/fsw/FCCode/PropController.cpp
>      manual_eval(controller->sched_intertank1_f, Tank2, 0);
just wondering but should this be `manual_eval(controller->sched_intertank1_f, Tank1, 0);`?

2021-05-13 15:07 UTC, tanishqaggarwal commented on ptest/cases/mission/near_field.py
> +        # self.psim_config_overrides = {"truth.leader.pos": lin.Vector3[0,0,0,0], "truth.leader.vel"}
```suggestion
```

2021-05-13 15:07 UTC, tanishqaggarwal commented on ptest/cases/mission/near_field.py
> +        # self.flight_controller_leader.write_state("dcdc.SpikeDock_cmd
```suggestion
```

2021-05-13 15:07 UTC, tanishqaggarwal commented on ptest/cases/mission/utils.py
> +    #    "adcs_monitor.ssa_mode",
```suggestion
```

2021-05-13 15:07 UTC, tanishqaggarwal commented on src/flow_data.cpp
> +{27, false, {"prop.cycles_until_firing", "prop.sched_intertank1", "prop.sched_intertank2"}},
Why remove these values from flow data?

2021-05-13 15:07 UTC, tanishqaggarwal commented on src/fsw/FCCode/OrbitController.hpp
>       */
Add docstring for function arguments?

2021-05-13 15:07 UTC, tanishqaggarwal commented on src/fsw/FCCode/OrbitController.hpp
>       */
Add docstring for function arguments?

2021-05-13 15:07 UTC, tanishqaggarwal commented on src/fsw/FCCode/PropController.cpp
> +    }
Software design-wise, I feel like this logic should exist in orbit controller; prop controller shouldn't care about orbital state

2021-05-13 15:07 UTC, tanishqaggarwal commented on src/fsw/FCCode/PropController.cpp
> +      sched_valve4_fp(FIND_WRITABLE_FIELD(unsigned int, orbit.control.valve4)),
I see that the valve schedule fields have moved to orbit controller; but are we still able to test the prop system manually by setting schedules?

2021-05-18 03:18 UTC, shihaocao commented on src/fsw/FCCode/PropController.cpp
> +    }
We need to actually have two new statefields that are both Writable

`threshold_firing_that_is_actually_used` set to `thresh_1` in nominal conditions, but `thresh_2` when we are in near field

2021-05-19 23:27 UTC, shihaocao commented on test/test_fsw_prop_faults/test_prop_faults.cpp
> -    tf.pc->threshold_firing_pressure.set(14.0); // default fake pressure is 14.6 psi
This brings down the tunable field that we would use on the ground to fake it being above the threshold pressure

2021-05-20 13:20 UTC, fatimayousuf commented on src/flow_data.cpp
> +{27, false, {"prop.cycles_until_firing", "prop.sched_intertank1", "prop.sched_intertank2"}},
#761

2021-05-20 14:16 UTC, tanishqaggarwal commented on src/flow_data.cpp
> +{27, false, {"prop.cycles_until_firing", "prop.sched_intertank1", "prop.sched_intertank2"}},
Lol I'm blind, I see the orbit control valve state fields now

2021-05-20 21:23 UTC, fatimayousuf approved these changes

2021-05-21 03:04 UTC, merged