Quake fault handler HITL
pathfinder-for-autonomous-navigation/FlightSoftware pull request #786
Opened 2021-05-25 22:49 UTC by 18kudlugim

QFH PTest changes following HITL Testing:
- Needed to change the number of control cycles in a day to allow power cycling in HITL to complete in the smallest amount of time possible. Power cycling takes approximately 45 seconds in HITL to complete, and this must happen before the next power cycle is to take place. 
- For the above reasons, we created a QFH_SPEEDUP build flag that sets the tracked constant one_day_ccno to 1400.
- quake_power_cycling.py PTest formatting cleanup

2021-05-26 00:36 UTC, knk38 approved these changes
Looks great!

2021-05-26 00:36 UTC, knk38 commented on ptest/cases/quake_power_cycling.py
> +                    'forced_standby'] and not self.mission_state == "standby":
maybe move this back to be one line for readability sake

2021-05-26 01:06 UTC, fatimayousuf requested changes

2021-05-26 01:06 UTC, fatimayousuf commented on src/fsw/FCCode/constants.hpp
> +    # ifdef QFH_SPEEDUP
Can you make a new teensy36 pio environment that has the QFH SPEEDUP build flag? There's already one for the SPEEDUP flag, so you can mostly just copy that.

Then, in the mission procedures, we can tell them to upload this environment to the satellite before running this checkout case

2021-05-27 04:37 UTC, 18kudlugim commented on src/fsw/FCCode/constants.hpp
> +    # ifdef QFH_SPEEDUP
sounds good, I pushed the changes just now

2021-05-27 04:42 UTC, fatimayousuf approved these changes

2021-05-27 04:42 UTC, fatimayousuf commented on ptest/cases/quake_power_cycling.py
> +        # This step is necessary in HOOTL, must be commented out in HITL
Why is this step not necessary in HITL?

2021-05-30 23:21 UTC, 18kudlugim commented on ptest/cases/quake_power_cycling.py
> +        # This step is necessary in HOOTL, must be commented out in HITL
I think it has something to do with an external subsystem setting a value in HOOTL. I discussed this with @kylekrol earlier in the sem and it was determined to be HOOTL-only. Wasn't an issue when we ran it in HITL, though. If you run the qfh test in HOOTL and plot it you would probably see the issue with the first power cycle not happening, and only subsequent ones following expected behavior

2021-07-01 01:32 UTC, merged

2021-07-01 01:33 UTC, knk38 commented
Since this was hitl tested a few times it is good to go