Telemetry phases
pathfinder-for-autonomous-navigation/FlightSoftware pull request #817
Opened 2021-09-28 02:07 UTC by fatimayousuf

# Reorder Telemetry Flows if Faulted

### Summary of changes
- If. fault is signaled, the flow with all the faults in it (flow 7) will move to the third position in the flow order
- Once the fault is not faulted anymore, it will move back to its original position in the flow order

### Testing
- See the unit test in test_fsw_downlink_producer
- Signal a fault and check that flow 7 moves to the 3rd position
- Unsignal the fault and check that it goes back to its original position in the flow order

2021-09-28 05:21 UTC, shihaocao commented on src/fsw/FCCode/DownlinkProducer.cpp
> +    }
this method looks really big, and seems a bit confusing?

We know that all faults are going to always be in the same flow, so what if we wrote a function that returns true if any fault is faulted

Then if the above function returns true, we shift the fault flow to the top?

2021-09-28 05:24 UTC, shihaocao commented on src/fsw/FCCode/DownlinkProducer.cpp
> +                            faults_flow_shifted = true;
Can this logic be separated into its own function? Say some loop that searches through all flows, and returns as soon as it finds the flow that contains the "key" fault. Where the "key" fault is the first fault in the fault flow (I don't think we'll be changing whatever that fault is)

2021-09-28 05:25 UTC, shihaocao commented on src/fsw/FCCode/DownlinkProducer.cpp
> +        assert(false);
lets take out this debug code, or at least wrap it in a #IFNDEF flight or something

2021-09-28 05:27 UTC, shihaocao commented on src/fsw/FCCode/DownlinkProducer.hpp
> +     */
Can we fill this out? Just a few sentences is good haha thanks

2021-09-28 05:30 UTC, shihaocao requested changes
Functionality looks good, just wondering if it could be refactored a bit.

Question though: what happens in the future if a state change and we change the flow ordering for states? I guess we don't have to bake it into this PR, but we should update the ticket with how this system will be easily upgradable and wont interfere with state changes n stuff.

2021-09-28 05:59 UTC, fatimayousuf commented on src/fsw/FCCode/DownlinkProducer.cpp
> +    }
The faults will always be in the same flow, that's true. but we also need to know the original index position of this flow for when the fault is eventually unfaulted and we have to move it back. that's why we have all this loop stuff going on.

Also this method doesn't return anything, it will shift the flow whenever a fault in the active_faults list is faulted.

2021-09-28 05:59 UTC, fatimayousuf commented on src/fsw/FCCode/DownlinkProducer.cpp
> +    }
ok should I do the same for `shift_flow_priorities()`

2021-09-28 06:00 UTC, fatimayousuf commented on src/fsw/FCCode/DownlinkProducer.hpp
> +     */
oops forgot about that sorry

2021-09-28 06:03 UTC, fatimayousuf commented
> Functionality looks good, just wondering if it could be refactored a bit.
> 
> Question though: what happens in the future if a state change and we change the flow ordering for states? I guess we don't have to bake it into this PR, but we should update the ticket with how this system will be easily upgradable and wont interfere with state changes n stuff.

yeah so Angela and I changed this a bit since our last discussion. now, before shifting a flow upwards in the flow order, we save the original _index_ of the flow with faults (not the id of the flow behind it). We also wrote a new function to shift the flow with a given flow id to a new index (as opposed to taking two flow ids as parameters). So this helps us get around changes in the telemetry flow ordering due to changes in mission state.

2021-09-28 16:32 UTC, knk38 commented
Okay I'll wait until the next commit to add my review, but I agree with shihao's notes

2021-10-02 16:50 UTC, knk38 approved these changes
looks good :)

2021-10-02 16:50 UTC, knk38 commented on src/fsw/FCCode/DownlinkProducer.cpp
> +        FIND_FAULT(adcs_monitor.wheel1_fault.base), // this one isnt in flow_data.cpp
@shihaocao Any reason why this fault isnt in the flow_data.cpp vector? If not I think we should add lol

2021-10-02 17:54 UTC, shihaocao approved these changes
Great stuff, love the refactor too

2021-10-02 17:55 UTC, merged